// Generated by vexel from format `csv`. Do not edit by hand;
// regenerate with `cargo run --example generate` (in-tree) or the vexel CLI.
//
// Structural indexer: appends to `out` the byte offset of every set bit in
// the format's output bitstream (its structural positions). Self-contained:
// depends only on std.
//
// Also exposes a span API: `parse(data)` -> `records()` -> `field(i)`,
// with dialect-aware quote stripping and escape resolution.

/// Index the structural positions of `data` into `out`.
pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx2::index_structurals(data, out) };
        return;
    }
    fallback::index_structurals(data, out);
}

/// Index `data` and return a lazy record/field view over it.
pub fn parse(data: &[u8]) -> Parsed<'_> {
    let mut structurals = Vec::with_capacity(data.len() / 16 + 8);
    index_structurals(data, &mut structurals);
    Parsed { data, structurals }
}

/// A structural index over borrowed input.
pub struct Parsed<'a> {
    data: &'a [u8],
    structurals: Vec<u32>,
}

impl<'a> Parsed<'a> {
    /// The raw structural positions (unquoted separators and terminators).
    pub fn structurals(&self) -> &[u32] {
        &self.structurals
    }

    /// Iterate records (lines outside quoted regions). A record's trailing
    /// `\r` is trimmed; an empty line yields a record with one empty field.
    pub fn records(&self) -> Records<'_> {
        Records {
            data: self.data,
            structurals: &self.structurals,
            byte_pos: 0,
            idx: 0,
        }
    }
}

pub struct Records<'p> {
    data: &'p [u8],
    structurals: &'p [u32],
    byte_pos: usize,
    idx: usize,
}

impl<'p> Iterator for Records<'p> {
    type Item = Record<'p>;

    fn next(&mut self) -> Option<Record<'p>> {
        let start = self.byte_pos;
        if start >= self.data.len() {
            return None;
        }
        let sep_start = self.idx;
        let mut i = self.idx;
        let mut end = self.data.len();
        let mut next_start = self.data.len();
        while i < self.structurals.len() {
            let pos = self.structurals[i] as usize;
            if self.data[pos] == b'\n' {
                end = pos;
                next_start = pos + 1;
                break;
            }
            i += 1;
        }
        let seps = &self.structurals[sep_start..i];
        self.idx = if i < self.structurals.len() { i + 1 } else { i };
        self.byte_pos = next_start;
        let end = if end > start && self.data[end - 1] == b'\r' {
            end - 1
        } else {
            end
        };
        Some(Record { data: self.data, start, end, seps })
    }
}

/// One record: a span of input plus the separator positions inside it.
#[derive(Clone, Copy)]
pub struct Record<'p> {
    data: &'p [u8],
    start: usize,
    end: usize,
    seps: &'p [u32],
}

impl<'p> Record<'p> {
    /// The whole record span, terminator excluded.
    pub fn as_bytes(&self) -> &'p [u8] {
        &self.data[self.start..self.end]
    }

    pub fn field_count(&self) -> usize {
        self.seps.len() + 1
    }

    /// Raw span of field `i`: quotes and escapes intact.
    pub fn field_raw(&self, i: usize) -> Option<&'p [u8]> {
        if i > self.seps.len() {
            return None;
        }
        let from = if i == 0 {
            self.start
        } else {
            self.seps[i - 1] as usize + 1
        };
        let to = if i == self.seps.len() {
            self.end
        } else {
            self.seps[i] as usize
        };
        Some(&self.data[from..to])
    }

    /// Field `i` with surrounding quotes stripped and escapes resolved;
    /// borrows unless an escape sequence forces a copy.
    pub fn field(&self, i: usize) -> Option<std::borrow::Cow<'p, [u8]>> {
        self.field_raw(i).map(clean)
    }

    pub fn fields(&self) -> impl Iterator<Item = std::borrow::Cow<'p, [u8]>> + '_ {
        (0..self.field_count()).map(move |i| self.field(i).expect("index in range"))
    }
}

/// Strip surrounding quotes and collapse doubled escape quotes.
fn clean(raw: &[u8]) -> std::borrow::Cow<'_, [u8]> {
    const Q: u8 = 34u8;
    if raw.len() >= 2 && raw[0] == Q && raw[raw.len() - 1] == Q {
        let inner = &raw[1..raw.len() - 1];
        if !inner.windows(2).any(|w| w[0] == Q && w[1] == Q) {
            return std::borrow::Cow::Borrowed(inner);
        }
        let mut out = Vec::with_capacity(inner.len());
        let mut i = 0;
        while i < inner.len() {
            out.push(inner[i]);
            if inner[i] == Q && i + 1 < inner.len() && inner[i + 1] == Q {
                i += 2;
            } else {
                i += 1;
            }
        }
        return std::borrow::Cow::Owned(out);
    }
    std::borrow::Cow::Borrowed(raw)
}

/// Portable kernel, public so the dispatch-bypassed path stays testable.
pub mod fallback {
    pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {
        let mut carries = [0u64; 1];
        let mut offset = 0usize;
        while offset + 64 <= data.len() {
            let block: &[u8; 64] = data[offset..offset + 64].try_into().unwrap();
            let mask = step(block, &mut carries);
            push_indexes(mask, offset as u32, out);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            // Mask off bits that fall in the zero padding.
            let mask = step(&block, &mut carries) & ((1u64 << rem) - 1);
            push_indexes(mask, offset as u32, out);
        }
    }

    #[inline]
    fn step(block: &[u8; 64], carries: &mut [u64; 1]) -> u64 {
        let v0 = eq_mask(block, 10u8) | eq_mask(block, 44u8); // class "\n,"
        let v1 = eq_mask(block, 34u8); // class "\""
        let v2 = { let parity = prefix_xor(v1) ^ carries[0]; carries[0] = ((parity as i64) >> 63) as u64; parity };
        let v3 = !v2;
        let v4 = v0 & v3;
        v4
    }

    #[inline]
    fn eq_mask(block: &[u8; 64], byte: u8) -> u64 {
        let mut mask = 0u64;
        let mut i = 0;
        while i < 64 {
            mask |= ((block[i] == byte) as u64) << i;
            i += 1;
        }
        mask
    }

    #[inline]
    fn prefix_xor(mut x: u64) -> u64 {
        x ^= x << 1;
        x ^= x << 2;
        x ^= x << 4;
        x ^= x << 8;
        x ^= x << 16;
        x ^= x << 32;
        x
    }

    #[inline]
    fn push_indexes(mut mask: u64, base: u32, out: &mut Vec<u32>) {
        while mask != 0 {
            out.push(base + mask.trailing_zeros());
            mask &= mask - 1;
        }
    }
}

#[cfg(target_arch = "x86_64")]
mod avx2 {
    use std::arch::x86_64::*;

    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {
        let mut carries = [0u64; 1];
        let mut offset = 0usize;
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let mask = unsafe { step(data.as_ptr().add(offset), &mut carries) };
            push_indexes(mask, offset as u32, out);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let mask = unsafe { step(block.as_ptr(), &mut carries) } & ((1u64 << rem) - 1);
            push_indexes(mask, offset as u32, out);
        }
    }

    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    unsafe fn step(ptr: *const u8, carries: &mut [u64; 1]) -> u64 {
        // SAFETY: caller guarantees 64 readable bytes at `ptr`.
        let (lo, hi) = unsafe {
            (
                _mm256_loadu_si256(ptr as *const __m256i),
                _mm256_loadu_si256(ptr.add(32) as *const __m256i),
            )
        };
        let v0 = eq_mask(lo, hi, 10u8) | eq_mask(lo, hi, 44u8); // class "\n,"
        let v1 = eq_mask(lo, hi, 34u8); // class "\""
        let v2 = { let parity = prefix_xor(v1) ^ carries[0]; carries[0] = ((parity as i64) >> 63) as u64; parity };
        let v3 = !v2;
        let v4 = v0 & v3;
        v4
    }

    #[target_feature(enable = "avx2")]
    fn eq_mask(lo: __m256i, hi: __m256i, byte: u8) -> u64 {
        let needle = _mm256_set1_epi8(byte as i8);
        let lo_bits = _mm256_movemask_epi8(_mm256_cmpeq_epi8(lo, needle)) as u32 as u64;
        let hi_bits = _mm256_movemask_epi8(_mm256_cmpeq_epi8(hi, needle)) as u32 as u64;
        lo_bits | (hi_bits << 32)
    }

    #[target_feature(enable = "pclmulqdq")]
    fn prefix_xor(mask: u64) -> u64 {
        let ones = _mm_set1_epi8(-1);
        let value = _mm_set_epi64x(0, mask as i64);
        let product = _mm_clmulepi64_si128::<0>(value, ones);
        _mm_cvtsi128_si64(product) as u64
    }

    /// Branchless bit decoding (simdjson flatten_bits): write indexes in
    /// unconditional chunks of 8, then expose only the popcount-many real
    /// entries.
    #[inline]
    fn push_indexes(mut mask: u64, base: u32, out: &mut Vec<u32>) {
        let count = mask.count_ones() as usize;
        if count == 0 {
            return;
        }
        let len = out.len();
        out.reserve(count + 8);
        // SAFETY: capacity covers len + count + 8; chunked writes overshoot
        // by at most 7 entries and set_len exposes only the real ones.
        unsafe {
            let mut ptr = out.as_mut_ptr().add(len);
            let mut remaining = count as isize;
            while remaining > 0 {
                let mut j = 0;
                while j < 8 {
                    *ptr.add(j) = base + mask.trailing_zeros();
                    mask &= mask.wrapping_sub(1);
                    j += 1;
                }
                ptr = ptr.add(8);
                remaining -= 8;
            }
            out.set_len(len + count);
        }
    }
}
