// Generated by falx from format `fastq`. Do not edit by hand;
// regenerate with `cargo run --example generate` (in-tree) or the falx CLI.
//
// Structural indexer: appends to `out` the byte offset of every set bit in
// the format's output bitstream (its structural positions). Self-contained:
// depends only on std.
//
// Also exposes a span API: `parse(data)` -> `records()` -> `field(i)`,
// with dialect-aware quote stripping and escape resolution.

#[rustfmt::skip]
mod generated {
/// Index the structural positions of `data` into `out`.
pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx512f")
        && std::arch::is_x86_feature_detected!("avx512bw")
        && std::arch::is_x86_feature_detected!("avx512vl")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx512::index_structurals(data, out) };
        return;
    }
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx2::index_structurals(data, out) };
        return;
    }
    unsupported_cpu();
}

fn unsupported_cpu() -> ! {
    panic!("falx generated kernels require x86_64 AVX2+PCLMULQDQ or AVX-512F/BW/VL+PCLMULQDQ");
}



/// One chunk's tape: separator positions and end entries.
type TapePart = (Vec<u32>, Vec<u64>);

/// Parallel structural indexing: byte-identical to [`index_structurals`],
/// split across `threads` chunks. Each chunk is indexed speculatively as if
/// it started outside a quoted region; its quote parity falls out of the
/// kernel's final carry, so there is no separate counting prepass over the
/// data. The rare chunk that truly began inside a quoted field is re-indexed.
pub fn index_structurals_par(data: &[u8], threads: usize, out: &mut Vec<u32>) {
    let threads = threads.max(1).min(data.len() / 64 + 1);
    let chunk = (data.len() / threads + 63) & !63;
    if threads == 1 || chunk == 0 {
        index_structurals(data, out);
        return;
    }
    let bounds: Vec<usize> = (0..=threads)
        .map(|t| if t == threads { data.len() } else { (t * chunk).min(data.len()) })
        .collect();
    let mut results: Vec<(Vec<u32>, u64)> = std::thread::scope(|s| {
        let handles: Vec<_> = (0..threads)
            .map(|t| {
                let slice = &data[bounds[t]..bounds[t + 1]];
                let base = bounds[t] as u32;
                s.spawn(move || {
                    let mut part = Vec::with_capacity(slice.len() / 16 + 8);
                    let carry = index_structurals_seeded_dispatch(slice, 0, base, &mut part);
                    (part, carry)
                })
            })
            .collect();
        handles.into_iter().map(|h| h.join().expect("index thread ok")).collect()
    });
    let mut entry = 0u64;
    let mut redo: Vec<usize> = Vec::new();
    for (t, r) in results.iter().enumerate() {
        if entry != 0 {
            redo.push(t);
        }
        entry ^= r.1;
    }
    if !redo.is_empty() {
        let redone: Vec<(usize, Vec<u32>)> = std::thread::scope(|s| {
            let handles: Vec<_> = redo
                .iter()
                .map(|&t| {
                    let slice = &data[bounds[t]..bounds[t + 1]];
                    let base = bounds[t] as u32;
                    s.spawn(move || {
                        let mut part = Vec::with_capacity(slice.len() / 16 + 8);
                        index_structurals_seeded_dispatch(slice, u64::MAX, base, &mut part);
                        (t, part)
                    })
                })
                .collect();
            handles.into_iter().map(|h| h.join().expect("redo thread ok")).collect()
        });
        for (t, part) in redone {
            results[t].0 = part;
        }
    }
    let parts: Vec<Vec<u32>> = results.into_iter().map(|r| r.0).collect();
    scatter_u32(out, &parts);
}

/// Append per-chunk index parts to `out`, copying each into its own disjoint
/// slot concurrently. The previous single-threaded concat serialized an
/// O(positions) copy and was the parallel scaling ceiling.
fn scatter_u32(out: &mut Vec<u32>, parts: &[Vec<u32>]) {
    let total: usize = parts.iter().map(|p| p.len()).sum();
    let start = out.len();
    out.reserve(total);
    {
        let mut rest = &mut out.spare_capacity_mut()[..total];
        let mut slots: Vec<&mut [std::mem::MaybeUninit<u32>]> = Vec::with_capacity(parts.len());
        for p in parts {
            let (head, tail) = rest.split_at_mut(p.len());
            slots.push(head);
            rest = tail;
        }
        std::thread::scope(|s| {
            for (slot, part) in slots.into_iter().zip(parts.iter()) {
                s.spawn(move || {
                    // SAFETY: slot.len() == part.len(); the copy initializes
                    // exactly this disjoint slice of `out`'s spare capacity.
                    unsafe {
                        std::ptr::copy_nonoverlapping(
                            part.as_ptr(),
                            slot.as_mut_ptr().cast::<u32>(),
                            part.len(),
                        );
                    }
                });
            }
        });
    }
    // SAFETY: the scatter initialized every element of spare[..total].
    unsafe { out.set_len(start + total); }
}

fn index_structurals_seeded_dispatch(data: &[u8], seed: u64, base: u32, out: &mut Vec<u32>) -> u64 {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx512f")
        && std::arch::is_x86_feature_detected!("avx512bw")
        && std::arch::is_x86_feature_detected!("avx512vl")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        return unsafe { avx512::index_structurals_seeded(data, seed, base, out) };
    }
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        return unsafe { avx2::index_structurals_seeded(data, seed, base, out) };
    }
    unsupported_cpu()
}

/// Parallel [`parse`]: identical tape, built across `threads` chunks.
pub fn parse_par(data: &[u8], threads: usize) -> Parsed<'_> {
    let threads = threads.max(1).min(data.len() / 64 + 1);
    let chunk = (data.len() / threads + 63) & !63;
    if threads == 1 || chunk == 0 {
        return parse(data);
    }
    let bounds: Vec<usize> = (0..=threads)
        .map(|t| if t == threads { data.len() } else { (t * chunk).min(data.len()) })
        .collect();
    let mut results: Vec<(TapePart, u64)> = std::thread::scope(|s| {
        let handles: Vec<_> = (0..threads)
            .map(|t| {
                let slice = &data[bounds[t]..bounds[t + 1]];
                let base = bounds[t] as u32;
                s.spawn(move || {
                    let mut seps = Vec::with_capacity(slice.len() / 16 + 8);
                    let mut ends = Vec::with_capacity(slice.len() / 32 + 8);
                    let carry = index_tape_seeded_dispatch(slice, 0, base, &mut seps, &mut ends);
                    ((seps, ends), carry)
                })
            })
            .collect();
        handles.into_iter().map(|h| h.join().expect("parse thread ok")).collect()
    });
    let mut entry = 0u64;
    let mut redo: Vec<usize> = Vec::new();
    for (t, r) in results.iter().enumerate() {
        if entry != 0 {
            redo.push(t);
        }
        entry ^= r.1;
    }
    if !redo.is_empty() {
        let redone: Vec<(usize, TapePart)> = std::thread::scope(|s| {
            let handles: Vec<_> = redo
                .iter()
                .map(|&t| {
                    let slice = &data[bounds[t]..bounds[t + 1]];
                    let base = bounds[t] as u32;
                    s.spawn(move || {
                        let mut seps = Vec::with_capacity(slice.len() / 16 + 8);
                        let mut ends = Vec::with_capacity(slice.len() / 32 + 8);
                        index_tape_seeded_dispatch(slice, u64::MAX, base, &mut seps, &mut ends);
                        (t, (seps, ends))
                    })
                })
                .collect();
            handles.into_iter().map(|h| h.join().expect("redo thread ok")).collect()
        });
        for (t, part) in redone {
            results[t].0 = part;
        }
    }
    let parts: Vec<TapePart> = results.into_iter().map(|r| r.0).collect();
    let (seps, ends) = scatter_tape(&parts);
    Parsed { data, seps, ends }
}

/// Concatenate per-chunk tape parts into the master tape, copying each into
/// its own disjoint slot concurrently. Separator positions and end byte
/// offsets are already absolute; only each end entry's cumulative-separator
/// high word is rebased by the separators in the preceding chunks.
fn scatter_tape(parts: &[TapePart]) -> (Vec<u32>, Vec<u64>) {
    let sep_total: usize = parts.iter().map(|p| p.0.len()).sum();
    let end_total: usize = parts.iter().map(|p| p.1.len()).sum();
    let mut seps: Vec<u32> = Vec::with_capacity(sep_total);
    let mut ends: Vec<u64> = Vec::with_capacity(end_total);
    // Cumulative separator count before each chunk (the ends rebase amount).
    let mut sep_prefix: Vec<u64> = Vec::with_capacity(parts.len());
    {
        let mut acc = 0u64;
        for p in parts {
            sep_prefix.push(acc);
            acc += p.0.len() as u64;
        }
    }
    {
        let mut srest = &mut seps.spare_capacity_mut()[..sep_total];
        let mut erest = &mut ends.spare_capacity_mut()[..end_total];
        let mut sslots: Vec<&mut [std::mem::MaybeUninit<u32>]> = Vec::with_capacity(parts.len());
        let mut eslots: Vec<&mut [std::mem::MaybeUninit<u64>]> = Vec::with_capacity(parts.len());
        for p in parts {
            let (sh, st) = srest.split_at_mut(p.0.len());
            sslots.push(sh);
            srest = st;
            let (eh, et) = erest.split_at_mut(p.1.len());
            eslots.push(eh);
            erest = et;
        }
        std::thread::scope(|s| {
            for (((sslot, eslot), part), &prefix) in
                sslots.into_iter().zip(eslots).zip(parts.iter()).zip(sep_prefix.iter())
            {
                s.spawn(move || {
                    // SAFETY: each slot's length equals its part's; the writes
                    // initialize exactly these disjoint slices.
                    unsafe {
                        std::ptr::copy_nonoverlapping(
                            part.0.as_ptr(),
                            sslot.as_mut_ptr().cast::<u32>(),
                            part.0.len(),
                        );
                    }
                    let rebase = prefix << 32;
                    let dst = eslot.as_mut_ptr().cast::<u64>();
                    for (i, &e) in part.1.iter().enumerate() {
                        // SAFETY: i < part.1.len() == eslot.len().
                        unsafe { *dst.add(i) = e + rebase; }
                    }
                });
            }
        });
    }
    // SAFETY: the scatter initialized every element of both spare regions.
    unsafe {
        seps.set_len(sep_total);
        ends.set_len(end_total);
    }
    (seps, ends)
}

fn index_tape_seeded_dispatch(data: &[u8], seed: u64, base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) -> u64 {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx512f")
        && std::arch::is_x86_feature_detected!("avx512bw")
        && std::arch::is_x86_feature_detected!("avx512vl")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        return unsafe { avx512::index_tape_seeded(data, seed, base, seps, ends) };
    }
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        return unsafe { avx2::index_tape_seeded(data, seed, base, seps, ends) };
    }
    unsupported_cpu()
}
/// Record-aware tape indexing used by [`parse`].
fn index_tape(data: &[u8], seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx512f")
        && std::arch::is_x86_feature_detected!("avx512bw")
        && std::arch::is_x86_feature_detected!("avx512vl")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx512::index_tape(data, seps, ends) };
        return;
    }
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx2::index_tape(data, seps, ends) };
        return;
    }
    unsupported_cpu();
}

/// Index `data` and return a lazy record/field view over it.
pub fn parse(data: &[u8]) -> Parsed<'_> {
    let mut seps = Vec::with_capacity(data.len() / 16 + 8);
    let mut ends = Vec::with_capacity(data.len() / 32 + 8);
    index_tape(data, &mut seps, &mut ends);
    Parsed { data, seps, ends }
}

/// Like [`parse`], recycling the tape allocations of a previous parse (its
/// contents are discarded). At GiB/s the soft page faults of fresh tape
/// buffers are a measurable share of a parse; steady-state callers — one
/// parse per batch, file, or request — avoid them entirely.
pub fn parse_into<'a>(data: &'a [u8], recycle: Parsed<'_>) -> Parsed<'a> {
    let mut seps = recycle.seps;
    let mut ends = recycle.ends;
    seps.clear();
    ends.clear();
    index_tape(data, &mut seps, &mut ends);
    Parsed { data, seps, ends }
}

/// A structural tape over borrowed input: separator positions plus record
/// ends carrying cumulative separator counts, so record iteration is O(1)
/// per record and never rescans the input.
pub struct Parsed<'a> {
    data: &'a [u8],
    seps: Vec<u32>,
    ends: Vec<u64>,
}

impl<'a> Parsed<'a> {
    /// Iterate records (lines outside quoted regions). A record's trailing
    /// `\r` is trimmed; an empty line yields a record with one empty field.
    pub fn records(&self) -> Records<'_> {
        self.records_range(0..self.ends.len())
    }

    /// Number of newline-terminated records (a trailing unterminated record
    /// is not counted but is still yielded by iteration).
    pub fn terminated_record_count(&self) -> usize {
        self.ends.len()
    }

    /// Iterate a sub-range of terminated records. Disjoint ranges cover
    /// disjoint input and can be walked from different threads — the
    /// building block for parallel record processing. The range ending at
    /// `terminated_record_count()` also yields any trailing unterminated
    /// record.
    pub fn records_range(&self, range: std::ops::Range<usize>) -> Records<'_> {
        let (byte_pos, sep_pos) = if range.start == 0 {
            (0, 0)
        } else {
            let prev = self.ends[range.start - 1];
            ((prev & 0xFFFF_FFFF) as usize + 1, (prev >> 32) as usize)
        };
        let data_end = if range.start >= range.end && !self.ends.is_empty() {
            byte_pos // empty sub-range: fence immediately, yield nothing
        } else if range.end == self.ends.len() {
            self.data.len()
        } else {
            // Coverage fence: the byte after this chunk's last terminator.
            (self.ends[range.end - 1] & 0xFFFF_FFFF) as usize + 1
        };
        Records {
            data: self.data,
            seps: &self.seps,
            ends: &self.ends[..range.end],
            next_end: range.start,
            byte_pos,
            sep_pos,
            data_end,
        }
    }
}

pub struct Records<'p> {
    data: &'p [u8],
    seps: &'p [u32],
    ends: &'p [u64],
    next_end: usize,
    byte_pos: usize,
    sep_pos: usize,
    /// Trailing-record fence: iteration past the last tape entry stops here.
    data_end: usize,
}

impl<'p> Records<'p> {
    /// Produce the next record in tape order, comment lines included.
    fn next_raw(&mut self) -> Option<Record<'p>> {
        let start = self.byte_pos;
        let (end, seps) = if self.next_end < self.ends.len() {
            let entry = self.ends[self.next_end];
            self.next_end += 1;
            let end = (entry & 0xFFFF_FFFF) as usize;
            let cum = (entry >> 32) as usize;
            let seps = &self.seps[self.sep_pos..cum];
            self.sep_pos = cum;
            self.byte_pos = end + 1;
            (end, seps)
        } else {
            // Trailing record without a newline (only at the true data end).
            if start >= self.data_end {
                return None;
            }
            let seps = &self.seps[self.sep_pos..];
            self.sep_pos = self.seps.len();
            self.byte_pos = self.data_end;
            (self.data_end, seps)
        };
        Some(Record { data: self.data, start, end, seps })
    }
}

impl<'p> Iterator for Records<'p> {
    type Item = Record<'p>;

    fn next(&mut self) -> Option<Record<'p>> {
        self.next_raw()
    }
}

/// One record: a span of input plus the separator positions inside it.
/// The `\r` of a `\r\n` terminator is trimmed lazily, where bytes are
/// actually read, so tape-only walks never touch the input buffer.
#[derive(Clone, Copy)]
pub struct Record<'p> {
    data: &'p [u8],
    start: usize,
    end: usize,
    seps: &'p [u32],
}

impl<'p> Record<'p> {
    /// Record end with a trailing `\r` (of `\r\n`) trimmed.
    #[inline]
    fn trimmed_end(&self) -> usize {
        if self.end > self.start && self.data[self.end - 1] == b'\r' {
            self.end - 1
        } else {
            self.end
        }
    }

    /// The whole record span, terminator excluded.
    pub fn as_bytes(&self) -> &'p [u8] {
        &self.data[self.start..self.trimmed_end()]
    }

    pub fn field_count(&self) -> usize {
        self.seps.len() + 1
    }

    /// Byte-offset span `(from, to)` of field `i`, quotes and escapes
    /// intact; offsets index the buffer the tape was built over.
    pub fn field_span(&self, i: usize) -> Option<(u32, u32)> {
        if i > self.seps.len() {
            return None;
        }
        let from = if i == 0 {
            self.start
        } else {
            self.seps[i - 1] as usize + 1
        };
        let to = if i == self.seps.len() {
            self.trimmed_end()
        } else {
            self.seps[i] as usize
        };
        Some((from as u32, to as u32))
    }

    /// Raw span of field `i`: quotes and escapes intact.
    pub fn field_raw(&self, i: usize) -> Option<&'p [u8]> {
        self.field_span(i)
            .map(|(from, to)| &self.data[from as usize..to as usize])
    }

    /// Field `i` with surrounding quotes stripped and escapes resolved;
    /// borrows unless an escape sequence forces a copy.
    pub fn field(&self, i: usize) -> Option<std::borrow::Cow<'p, [u8]>> {
        self.field_raw(i).map(clean)
    }

    pub fn fields(&self) -> Fields<'p> {
        Fields {
            data: self.data,
            seps: self.seps,
            next_sep: 0,
            from: self.start,
            end: self.trimmed_end(),
            done: false,
        }
    }

    /// Zero-copy field iterator: raw `&[u8]` spans with quotes and escapes
    /// intact — no `Cow`, no cleaning. The fastest field walk, for callers
    /// that handle (or don't need) quote stripping themselves.
    pub fn fields_raw(&self) -> FieldsRaw<'p> {
        FieldsRaw {
            data: self.data,
            seps: self.seps,
            next_sep: 0,
            from: self.start,
            end: self.trimmed_end(),
            done: false,
        }
    }
}

/// Field iterator: one running offset, one separator-slice cursor — no
/// per-field bounds re-derivation.
pub struct Fields<'p> {
    data: &'p [u8],
    seps: &'p [u32],
    next_sep: usize,
    from: usize,
    end: usize,
    done: bool,
}

impl<'p> Iterator for Fields<'p> {
    type Item = std::borrow::Cow<'p, [u8]>;

    #[inline]
    fn next(&mut self) -> Option<Self::Item> {
        if self.next_sep < self.seps.len() {
            // SAFETY: next_sep was just bounds-checked, and tape invariants
            // make the derived span valid: separator positions are strictly
            // increasing offsets into `data`, and `from` is either the
            // record start or one past the previous separator, so
            // from <= to < data.len() always holds. Fields walking is the
            // per-field hot path; the redundant checks measurably dominate
            // it for short fields.
            let span = unsafe {
                let to = *self.seps.get_unchecked(self.next_sep) as usize;
                self.next_sep += 1;
                let span = self.data.get_unchecked(self.from..to);
                self.from = to + 1;
                span
            };
            Some(clean(span))
        } else if !self.done {
            self.done = true;
            Some(clean(&self.data[self.from..self.end]))
        } else {
            None
        }
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let n = self.seps.len() - self.next_sep + (!self.done) as usize;
        (n, Some(n))
    }
}

/// Zero-copy variant of [`Fields`]: yields raw `&[u8]` spans, quotes and
/// escapes intact, with no `Cow` and no cleaning.
pub struct FieldsRaw<'p> {
    data: &'p [u8],
    seps: &'p [u32],
    next_sep: usize,
    from: usize,
    end: usize,
    done: bool,
}

impl<'p> Iterator for FieldsRaw<'p> {
    type Item = &'p [u8];

    #[inline]
    fn next(&mut self) -> Option<Self::Item> {
        if self.next_sep < self.seps.len() {
            // SAFETY: identical tape invariants to `Fields::next`.
            let span = unsafe {
                let to = *self.seps.get_unchecked(self.next_sep) as usize;
                self.next_sep += 1;
                let span = self.data.get_unchecked(self.from..to);
                self.from = to + 1;
                span
            };
            Some(span)
        } else if !self.done {
            self.done = true;
            Some(&self.data[self.from..self.end])
        } else {
            None
        }
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let n = self.seps.len() - self.next_sep + (!self.done) as usize;
        (n, Some(n))
    }
}

/// Incremental parser for unbounded input: feed chunks, receive complete
/// records via callback. Kernel carries persist across feeds, so quoted
/// regions and escape runs spanning chunk boundaries are handled exactly.
/// Bytes of the unfinished trailing record are buffered internally and
/// compacted amortized; a single record must fit in memory (< 4 GiB).
pub struct StreamParser {
    buf: Vec<u8>,
    seps: Vec<u32>,
    ends: Vec<u64>,
    indexed: usize,
    emitted: usize,
    emitted_seps: usize,
    record_start: usize,
    carries: [u64; 0],
}

/// Create a [`StreamParser`].
pub fn stream() -> StreamParser {
    StreamParser {
        buf: Vec::new(),
        seps: Vec::new(),
        ends: Vec::new(),
        indexed: 0,
        emitted: 0,
        emitted_seps: 0,
        record_start: 0,
        carries: [0u64; 0],
    }
}

impl StreamParser {
    /// Feed the next chunk; `on_record` is called once per record completed
    /// by this chunk.
    pub fn feed(&mut self, chunk: &[u8], mut on_record: impl FnMut(Record<'_>)) {
        self.buf.extend_from_slice(chunk);
        index_tape_partial_dispatch(
            &self.buf[self.indexed..],
            &mut self.carries,
            self.indexed as u32,
            &mut self.seps,
            &mut self.ends,
        );
        self.indexed += (self.buf.len() - self.indexed) & !63;
        self.emit_ready(&mut on_record);
        self.compact();
    }

    /// Signal end of input; emits any records completed by the final
    /// partial block plus a trailing unterminated record.
    pub fn finish(mut self, mut on_record: impl FnMut(Record<'_>)) {
        let rem = self.buf.len() - self.indexed;
        if rem > 0 {
            // True end of stream: zero padding is safe here, exactly as in
            // the batch tail.
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&self.buf[self.indexed..]);
            let live = (1u64 << rem) - 1;
            index_tape_block_dispatch(
                &block,
                live,
                &mut self.carries,
                self.indexed as u32,
                &mut self.seps,
                &mut self.ends,
            );
        }
        self.emit_ready(&mut on_record);
        if self.record_start < self.buf.len() {
            on_record(Record {
                data: &self.buf,
                start: self.record_start,
                end: self.buf.len(),
                seps: &self.seps[self.emitted_seps..],
            });
        }
    }

    fn emit_ready(&mut self, on_record: &mut impl FnMut(Record<'_>)) {
        while self.emitted < self.ends.len() {
            let entry = self.ends[self.emitted];
            let end = (entry & 0xFFFF_FFFF) as usize;
            let cum = (entry >> 32) as usize;
            on_record(Record {
                data: &self.buf,
                start: self.record_start,
                end,
                seps: &self.seps[self.emitted_seps..cum],
            });
            self.record_start = end + 1;
            self.emitted_seps = cum;
            self.emitted += 1;
        }
    }

    /// Drop consumed bytes/tape once they dominate the buffer. The cut is
    /// 64-byte aligned: it keeps block boundaries and, critically, byte
    /// position parity stable (the escape machinery's even/odd constant
    /// masks are parity-dependent).
    fn compact(&mut self) {
        let base = self.record_start.min(self.indexed) & !63;
        if base < 4096 || base < self.buf.len() / 2 {
            return;
        }
        self.buf.copy_within(base.., 0);
        self.buf.truncate(self.buf.len() - base);
        self.indexed -= base;
        self.seps.drain(..self.emitted_seps);
        for p in &mut self.seps {
            *p -= base as u32;
        }
        let rebase = ((self.emitted_seps as u64) << 32) | base as u64;
        self.ends.drain(..self.emitted);
        for e in &mut self.ends {
            *e -= rebase;
        }
        self.record_start -= base;
        self.emitted = 0;
        self.emitted_seps = 0;
    }
}

fn index_tape_partial_dispatch(data: &[u8], carries: &mut [u64; 0], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx512f")
        && std::arch::is_x86_feature_detected!("avx512bw")
        && std::arch::is_x86_feature_detected!("avx512vl")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx512::index_tape_partial(data, carries, base, seps, ends) };
        return;
    }
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx2::index_tape_partial(data, carries, base, seps, ends) };
        return;
    }
    unsupported_cpu();
}

fn index_tape_block_dispatch(block: &[u8; 64], live: u64, carries: &mut [u64; 0], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx512f")
        && std::arch::is_x86_feature_detected!("avx512bw")
        && std::arch::is_x86_feature_detected!("avx512vl")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx512::index_tape_block(block, live, carries, base, seps, ends) };
        return;
    }
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx2::index_tape_block(block, live, carries, base, seps, ends) };
        return;
    }
    unsupported_cpu();
}

/// No quote convention in this dialect: fields are returned verbatim.
#[inline]
fn clean(raw: &[u8]) -> std::borrow::Cow<'_, [u8]> {
    std::borrow::Cow::Borrowed(raw)
}


/// FASTQ parser summary emitted by [`parse_fastq`].
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct FastqStats {
    pub records: u64,
    pub sequence_bytes: u64,
    pub quality_bytes: u64,
    pub checksum: u64,
}

/// FASTQ validation error from the generated fixed-four-line parser.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FastqError {
    IncompleteRecord,
    BadHeader {
        offset: usize,
    },
    BadSeparator {
        offset: usize,
    },
    LengthMismatch {
        record: u64,
        sequence: usize,
        quality: usize,
    },
    TrailingBytes {
        offset: usize,
    },
}

/// Parse FASTQ records and return validated summary counters.
///
/// This is a generated domain API over the generated newline kernel: the SIMD
/// step emits newline masks, and a fixed-four-line sink validates FASTQ shape
/// while accumulating counters.
///
/// Strictness: a record is exactly four `\n`-terminated lines (`@` header,
/// sequence, `+` separator, quality) and the input must end with a newline —
/// a final record without a trailing `\n` is rejected (`IncompleteRecord` /
/// `TrailingBytes`). Bytes are taken verbatim: `\r` is not stripped, so CRLF
/// input either fails validation or counts the `\r` in line lengths and the
/// checksum. This is intentionally stricter than lenient FASTQ readers;
/// callers that must accept CRLF or an unterminated final record normalize
/// the input first.
pub fn parse_fastq(data: &[u8]) -> Result<FastqStats, FastqError> {
    let mut sink = FastqSink::new(data.len());
    fastq_blocks_dispatch(data, &mut sink)?;
    sink.finish()
}

/// Parallel FASTQ parser using generated mask streaming over record chunks.
///
/// A SIMD newline-count prepass finds true FASTQ record boundaries for worker
/// splits; each worker then streams generated newline masks directly into a
/// chunk-local [`FastqSink`]. This keeps the parallel path allocation-light:
/// it never materializes a full newline-position vector.
pub fn parse_fastq_par(data: &[u8], threads: usize) -> Result<FastqStats, FastqError> {
    let threads = threads.max(1).min(data.len() / 64 + 1);
    if threads == 1 || data.len() < (1 << 20) {
        return parse_fastq(data);
    }

    let Some(bounds) = fastq_record_bounds(data, threads) else {
        return parse_fastq(data);
    };
    let ranges: Vec<(usize, usize)> = bounds
        .windows(2)
        .filter_map(|w| (w[0] < w[1]).then_some((w[0], w[1])))
        .collect();
    if ranges.len() <= 1 {
        return parse_fastq(data);
    }

    let results: Vec<Result<FastqStats, FastqError>> = std::thread::scope(|s| {
        let handles: Vec<_> = ranges
            .iter()
            .map(|&(start, end)| {
                let slice = &data[start..end];
                s.spawn(move || {
                    let mut sink = FastqSink::new(slice.len());
                    fastq_blocks_dispatch(slice, &mut sink)?;
                    sink.finish()
                })
            })
            .collect();
        handles
            .into_iter()
            .map(|h| h.join().expect("fastq parse thread ok"))
            .collect()
    });

    let mut merged = FastqStats::default();
    for result in results {
        match result {
            Ok(stats) => merged.merge(stats),
            Err(_) => return parse_fastq(data),
        }
    }
    Ok(merged)
}

fn fastq_blocks_dispatch(data: &[u8], sink: &mut FastqSink) -> Result<(), FastqError> {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx512f")
        && std::arch::is_x86_feature_detected!("avx512bw")
        && std::arch::is_x86_feature_detected!("avx512vl")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        return unsafe { avx512::fastq_blocks(data, sink) };
    }
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        return unsafe { avx2::fastq_blocks(data, sink) };
    }
    unsupported_cpu()
}

fn fastq_record_bounds(data: &[u8], threads: usize) -> Option<Vec<usize>> {
    if data.is_empty() {
        return Some(vec![0]);
    }
    if data.last().copied() != Some(b'\n') {
        return None;
    }

    let threads = threads.max(1).min(data.len() / 64 + 1);
    let chunk = (data.len() / threads + 63) & !63;
    if threads == 1 || chunk == 0 {
        return Some(vec![0, data.len()]);
    }

    let approx: Vec<usize> = (0..=threads)
        .map(|t| {
            if t == threads {
                data.len()
            } else {
                (t * chunk).min(data.len())
            }
        })
        .collect();

    let mut bounds = Vec::with_capacity(threads + 1);
    bounds.push(0);
    for &target in approx.iter().take(threads).skip(1) {
        let bound = fastq_find_record_boundary(data, target)?;
        if bound > *bounds.last().expect("initial bound") && bound < data.len() {
            bounds.push(bound);
        }
    }
    bounds.push(data.len());
    Some(bounds)
}

/// Find a safe worker-split point at or after `offset`.
///
/// Splits must land on a true record start, so this scans forward to a line
/// beginning with `@` that revalidates as a complete four-line record
/// (`fastq_record_end_at`). A structurally wrong split makes a worker's sink
/// error and `parse_fastq_par` falls back to the serial parser, so a bad guess
/// cannot corrupt the result. The one residual (and vanishingly unlikely) case
/// is adversarial input where a quality line beginning with `@` coincidentally
/// starts a shape-valid four-line record at a chunk target: that can shift
/// framing without erroring, so the parallel record count is not trustworthy
/// on hostile, hand-crafted FASTQ.
fn fastq_find_record_boundary(data: &[u8], offset: usize) -> Option<usize> {
    if offset == 0 {
        return Some(0);
    }
    if offset >= data.len() {
        return Some(data.len());
    }

    let mut pos = offset;
    if data[pos - 1] != b'\n' {
        while pos < data.len() && data[pos] != b'\n' {
            pos += 1;
        }
        pos = pos.saturating_add(1);
    }

    while pos < data.len() {
        if data[pos] == b'@' && fastq_record_end_at(data, pos).is_some() {
            return Some(pos);
        }
        while pos < data.len() && data[pos] != b'\n' {
            pos += 1;
        }
        pos = pos.saturating_add(1);
    }
    Some(data.len())
}

fn fastq_record_end_at(data: &[u8], start: usize) -> Option<usize> {
    if data.get(start).copied() != Some(b'@') {
        return None;
    }
    let header_end = fastq_line_end(data, start)?;
    let sequence_start = header_end + 1;
    let sequence_end = fastq_line_end(data, sequence_start)?;
    let separator_start = sequence_end + 1;
    if data.get(separator_start).copied() != Some(b'+') {
        return None;
    }
    let separator_end = fastq_line_end(data, separator_start)?;
    let quality_start = separator_end + 1;
    let quality_end = fastq_line_end(data, quality_start)?;
    let sequence_len = sequence_end.checked_sub(sequence_start)?;
    let quality_len = quality_end.checked_sub(quality_start)?;
    (sequence_len == quality_len).then_some(quality_end + 1)
}

fn fastq_line_end(data: &[u8], start: usize) -> Option<usize> {
    data.get(start..)?
        .iter()
        .position(|&byte| byte == b'\n')
        .map(|end| start + end)
}

struct FastqSink {
    data_len: usize,
    line_start: usize,
    line_in_record: u8,
    sequence_start: usize,
    sequence_len: usize,
    error_quality_len: usize,
    checksum_lanes: [u64; 8],
    stats: FastqStats,
}

impl FastqSink {
    fn new(data_len: usize) -> Self {
        Self {
            data_len,
            line_start: 0,
            line_in_record: 0,
            sequence_start: 0,
            sequence_len: 0,
            error_quality_len: 0,
            checksum_lanes: [0; 8],
            stats: FastqStats::default(),
        }
    }

    #[cfg(target_arch = "x86_64")]
    #[target_feature(enable = "avx512f", enable = "avx512bw")]
    unsafe fn drive_avx512(
        &mut self,
        data: &[u8],
        mut mask: u64,
        base: usize,
        checksum_acc: &mut std::arch::x86_64::__m512i,
    ) -> u8 {
        while mask != 0 {
            let end = base + mask.trailing_zeros() as usize;
            let error = unsafe { self.line_avx512(data, end, checksum_acc) };
            if error != 0 {
                return error;
            }
            self.line_start = end + 1;
            mask &= mask - 1;
        }
        0
    }

    #[cfg(target_arch = "x86_64")]
    #[target_feature(enable = "avx512f", enable = "avx512bw")]
    unsafe fn drive_pair_avx512(
        &mut self,
        data: &[u8],
        m0: u64,
        m1: u64,
        base: usize,
        checksum_acc: &mut std::arch::x86_64::__m512i,
    ) -> u8 {
        let error = unsafe { self.drive_avx512(data, m0, base, checksum_acc) };
        if error != 0 {
            return error;
        }
        unsafe { self.drive_avx512(data, m1, base + 64, checksum_acc) }
    }

    #[cfg(target_arch = "x86_64")]
    #[target_feature(enable = "avx512f", enable = "avx512bw")]
    unsafe fn line_avx512(
        &mut self,
        data: &[u8],
        end: usize,
        checksum_acc: &mut std::arch::x86_64::__m512i,
    ) -> u8 {
        match self.line_in_record {
            0 => {
                if unsafe { *data.get_unchecked(self.line_start) } != b'@' {
                    return 1;
                }
                self.line_in_record = 1;
            }
            1 => {
                self.sequence_start = self.line_start;
                self.sequence_len = end - self.line_start;
                self.line_in_record = 2;
            }
            2 => {
                if unsafe { *data.get_unchecked(self.line_start) } != b'+' {
                    return 2;
                }
                self.line_in_record = 3;
            }
            _ => {
                return unsafe { self.record_avx512(data, end, checksum_acc) };
            }
        }
        0
    }

    #[cfg(target_arch = "x86_64")]
    #[target_feature(enable = "avx512f", enable = "avx512bw")]
    unsafe fn record_avx512(
        &mut self,
        data: &[u8],
        end: usize,
        checksum_acc: &mut std::arch::x86_64::__m512i,
    ) -> u8 {
        let quality_len = end - self.line_start;
        if quality_len != self.sequence_len {
            self.error_quality_len = quality_len;
            return 3;
        }
        let sequence = unsafe {
            data.get_unchecked(self.sequence_start..self.sequence_start + self.sequence_len)
        };
        let quality = unsafe { data.get_unchecked(self.line_start..end) };
        self.stats.records += 1;
        self.stats.sequence_bytes += sequence.len() as u64;
        self.stats.quality_bytes += quality.len() as u64;
        unsafe { checksum_fastq_record_avx512_acc(checksum_acc, sequence, quality) };
        self.line_in_record = 0;
        0
    }

    #[cfg(target_arch = "x86_64")]
    #[target_feature(enable = "avx2")]
    unsafe fn drive_avx2(
        &mut self,
        data: &[u8],
        mut mask: u64,
        base: usize,
        checksum_acc: &mut std::arch::x86_64::__m256i,
    ) -> u8 {
        while mask != 0 {
            let end = base + mask.trailing_zeros() as usize;
            let error = unsafe { self.line_avx2(data, end, checksum_acc) };
            if error != 0 {
                return error;
            }
            self.line_start = end + 1;
            mask &= mask - 1;
        }
        0
    }

    #[cfg(target_arch = "x86_64")]
    #[target_feature(enable = "avx2")]
    unsafe fn drive_pair_avx2(
        &mut self,
        data: &[u8],
        m0: u64,
        m1: u64,
        base: usize,
        checksum_acc: &mut std::arch::x86_64::__m256i,
    ) -> u8 {
        let error = unsafe { self.drive_avx2(data, m0, base, checksum_acc) };
        if error != 0 {
            return error;
        }
        unsafe { self.drive_avx2(data, m1, base + 64, checksum_acc) }
    }

    #[cfg(target_arch = "x86_64")]
    #[target_feature(enable = "avx2")]
    unsafe fn line_avx2(
        &mut self,
        data: &[u8],
        end: usize,
        checksum_acc: &mut std::arch::x86_64::__m256i,
    ) -> u8 {
        match self.line_in_record {
            0 => {
                if unsafe { *data.get_unchecked(self.line_start) } != b'@' {
                    return 1;
                }
                self.line_in_record = 1;
            }
            1 => {
                self.sequence_start = self.line_start;
                self.sequence_len = end - self.line_start;
                self.line_in_record = 2;
            }
            2 => {
                if unsafe { *data.get_unchecked(self.line_start) } != b'+' {
                    return 2;
                }
                self.line_in_record = 3;
            }
            _ => {
                return unsafe { self.record_avx2(data, end, checksum_acc) };
            }
        }
        0
    }

    #[cfg(target_arch = "x86_64")]
    #[target_feature(enable = "avx2")]
    unsafe fn record_avx2(
        &mut self,
        data: &[u8],
        end: usize,
        checksum_acc: &mut std::arch::x86_64::__m256i,
    ) -> u8 {
        let quality_len = end - self.line_start;
        if quality_len != self.sequence_len {
            self.error_quality_len = quality_len;
            return 3;
        }
        let sequence = unsafe {
            data.get_unchecked(self.sequence_start..self.sequence_start + self.sequence_len)
        };
        let quality = unsafe { data.get_unchecked(self.line_start..end) };
        self.stats.records += 1;
        self.stats.sequence_bytes += sequence.len() as u64;
        self.stats.quality_bytes += quality.len() as u64;
        unsafe { checksum_fastq_record_avx2_acc(checksum_acc, sequence, quality) };
        self.line_in_record = 0;
        0
    }

    #[cold]
    fn take_error(&self, code: u8) -> FastqError {
        match code {
            1 => FastqError::BadHeader {
                offset: self.line_start,
            },
            2 => FastqError::BadSeparator {
                offset: self.line_start,
            },
            3 => FastqError::LengthMismatch {
                record: self.stats.records,
                sequence: self.sequence_len,
                quality: self.error_quality_len,
            },
            _ => unreachable!("fastq sink error code"),
        }
    }

    fn finish(mut self) -> Result<FastqStats, FastqError> {
        if self.line_in_record != 0 {
            return Err(FastqError::IncompleteRecord);
        }
        if self.line_start != self.data_len {
            return Err(FastqError::TrailingBytes {
                offset: self.line_start,
            });
        }
        self.stats.checksum = finish_fastq_checksum(&self.checksum_lanes);
        Ok(self.stats)
    }
}

impl FastqStats {
    fn merge(&mut self, other: Self) {
        self.records += other.records;
        self.sequence_bytes += other.sequence_bytes;
        self.quality_bytes += other.quality_bytes;
        self.checksum = self.checksum.wrapping_add(other.checksum);
    }
}

#[inline]
fn finish_fastq_checksum(checksum_lanes: &[u64; 8]) -> u64 {
    checksum_lanes
        .iter()
        .fold(0u64, |checksum, lane| checksum.wrapping_add(*lane))
}

#[inline]
fn checksum_bytes_scalar(mut checksum: u64, bytes: &[u8]) -> u64 {
    let mut chunks = bytes.chunks_exact(8);
    for chunk in &mut chunks {
        let word = u64::from_le_bytes(chunk.try_into().expect("8-byte chunk"));
        let pairs = (word & 0x00ff_00ff_00ff_00ff) + ((word >> 8) & 0x00ff_00ff_00ff_00ff);
        let quads = (pairs & 0x0000_ffff_0000_ffff) + ((pairs >> 16) & 0x0000_ffff_0000_ffff);
        checksum = checksum.wrapping_add((quads & 0x0000_0000_ffff_ffff) + (quads >> 32));
    }
    for &byte in chunks.remainder() {
        checksum = checksum.wrapping_add(byte as u64);
    }
    checksum
}

#[cfg(target_arch = "x86_64")]
#[target_feature(enable = "avx512f", enable = "avx512bw")]
unsafe fn checksum_fastq_record_avx512_acc(
    acc: &mut std::arch::x86_64::__m512i,
    sequence: &[u8],
    quality: &[u8],
) {
    use std::arch::x86_64::{
        __m512i, __mmask64, _mm512_add_epi64, _mm512_loadu_si512, _mm512_maskz_loadu_epi8,
        _mm512_sad_epu8, _mm512_setzero_si512,
    };

    debug_assert_eq!(sequence.len(), quality.len());
    let zero = _mm512_setzero_si512();
    let mut local = *acc;
    let mut offset = 0usize;
    while offset + 64 <= sequence.len() {
        // SAFETY: offset + 64 <= both input lengths, so both unaligned loads are readable.
        let seq = unsafe { _mm512_loadu_si512(sequence.as_ptr().add(offset) as *const __m512i) };
        let qual = unsafe { _mm512_loadu_si512(quality.as_ptr().add(offset) as *const __m512i) };
        local = _mm512_add_epi64(local, _mm512_sad_epu8(seq, zero));
        local = _mm512_add_epi64(local, _mm512_sad_epu8(qual, zero));
        offset += 64;
    }
    let rem = sequence.len() - offset;
    if rem > 0 {
        let mask = ((1u64 << rem) - 1) as __mmask64;
        // SAFETY: the mask limits both loads to bytes within each slice.
        let seq = unsafe { _mm512_maskz_loadu_epi8(mask, sequence.as_ptr().add(offset) as *const i8) };
        let qual = unsafe { _mm512_maskz_loadu_epi8(mask, quality.as_ptr().add(offset) as *const i8) };
        local = _mm512_add_epi64(local, _mm512_sad_epu8(seq, zero));
        local = _mm512_add_epi64(local, _mm512_sad_epu8(qual, zero));
    }
    *acc = local;
}

#[cfg(target_arch = "x86_64")]
#[target_feature(enable = "avx2")]
unsafe fn checksum_fastq_record_avx2_acc(
    acc: &mut std::arch::x86_64::__m256i,
    sequence: &[u8],
    quality: &[u8],
) {
    use std::arch::x86_64::{
        __m256i, _mm256_add_epi64, _mm256_loadu_si256, _mm256_sad_epu8, _mm256_setzero_si256,
    };

    debug_assert_eq!(sequence.len(), quality.len());
    let zero = _mm256_setzero_si256();
    let mut local = *acc;
    let mut offset = 0usize;
    while offset + 32 <= sequence.len() {
        // SAFETY: offset + 32 <= both input lengths, so both unaligned loads are readable.
        let seq = unsafe { _mm256_loadu_si256(sequence.as_ptr().add(offset) as *const __m256i) };
        let qual = unsafe { _mm256_loadu_si256(quality.as_ptr().add(offset) as *const __m256i) };
        local = _mm256_add_epi64(local, _mm256_sad_epu8(seq, zero));
        local = _mm256_add_epi64(local, _mm256_sad_epu8(qual, zero));
        offset += 32;
    }
    *acc = local;
    checksum_lanes_tail(acc, &sequence[offset..], &quality[offset..]);
}

#[cfg(target_arch = "x86_64")]
fn checksum_lanes_tail(
    acc: &mut std::arch::x86_64::__m256i,
    sequence: &[u8],
    quality: &[u8],
) {
    use std::arch::x86_64::__m256i;

    // SAFETY: __m256i and [u64; 4] are both 32-byte vector storage here.
    let mut lanes: [u64; 4] = unsafe { std::mem::transmute::<__m256i, [u64; 4]>(*acc) };
    lanes[0] = checksum_bytes_scalar(lanes[0], sequence);
    lanes[0] = checksum_bytes_scalar(lanes[0], quality);
    // SAFETY: __m256i and [u64; 4] are both 32-byte vector storage here.
    *acc = unsafe { std::mem::transmute::<[u64; 4], __m256i>(lanes) };
}

#[cfg(target_arch = "x86_64")]
mod avx512 {
    use std::arch::x86_64::*;

    #[target_feature(enable = "avx512f", enable = "avx512bw", enable = "avx512vl", enable = "pclmulqdq")]
    pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {
        let mut offset = 0usize;
        // Two blocks per iteration: amortizes loop control and lets the
        // second block's classification overlap the first block's extract.
        while offset + 128 <= data.len() {
            // SAFETY: offset + 128 <= data.len(), so both blocks are readable.
            let m0 = unsafe { step(data.as_ptr().add(offset)) }.0;
            push_indexes(m0, offset as u32, out);
            let m1 = unsafe { step(data.as_ptr().add(offset + 64)) }.0;
            push_indexes(m1, (offset + 64) as u32, out);
            offset += 128;
        }
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let mask = unsafe { step(data.as_ptr().add(offset)) }.0;
            push_indexes(mask, offset as u32, out);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let mask = unsafe { step(block.as_ptr()) }.0 & ((1u64 << rem) - 1);
            push_indexes(mask, offset as u32, out);
        }
    }


    /// Record-aware indexing; structural and terminator masks encode the tape.
    #[target_feature(enable = "avx512f", enable = "avx512bw", enable = "avx512vl", enable = "pclmulqdq")]
    pub fn index_tape(data: &[u8], seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let mut offset = 0usize;
        // Two blocks per iteration (see index_structurals).
        while offset + 128 <= data.len() {
            // SAFETY: offset + 128 <= data.len(), so both blocks are readable.
            let (m0, t0) = unsafe { step(data.as_ptr().add(offset)) };
            push_tape(m0, t0, offset as u32, seps, ends);
            let (m1, t1) = unsafe { step(data.as_ptr().add(offset + 64)) };
            push_tape(m1, t1, (offset + 64) as u32, seps, ends);
            offset += 128;
        }
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let (mask, term) = unsafe { step(data.as_ptr().add(offset)) };
            push_tape(mask, term, offset as u32, seps, ends);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            let live = (1u64 << rem) - 1;
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let (mask, term) = unsafe { step(block.as_ptr()) };
            push_tape(mask & live, term & live, offset as u32, seps, ends);
        }
    }

    fn push_tape(structural: u64, term: u64, base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let sep_mask = structural & !term;
        let base_count = seps.len() as u64;
        push_indexes(sep_mask, base, seps);
        let mut t = term;
        while t != 0 {
            let idx = t.trailing_zeros();
            let below = (sep_mask & ((1u64 << idx) - 1)).count_ones() as u64;
            ends.push(((base_count + below) << 32) | (base + idx) as u64);
            t &= t - 1;
        }
    }

    /// Like `index_structurals` but seeded with the entry quote-parity carry
    /// and an absolute base offset; returns the *final* carry so the parallel
    /// driver can recover each chunk's quote parity without a counting prepass.
    #[target_feature(enable = "avx512f", enable = "avx512bw", enable = "avx512vl", enable = "pclmulqdq")]
    pub fn index_structurals_seeded(data: &[u8], seed: u64, base: u32, out: &mut Vec<u32>) -> u64 {
        let _ = seed;
        let mut offset = 0usize;
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len().
            let mask = unsafe { step(data.as_ptr().add(offset)) }.0;
            push_indexes(mask, base + offset as u32, out);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let mask = unsafe { step(block.as_ptr()) }.0 & ((1u64 << rem) - 1);
            push_indexes(mask, base + offset as u32, out);
        }
        0
    }

    /// Seeded-carry, based variant of `index_tape` for parallel parsing.
    #[target_feature(enable = "avx512f", enable = "avx512bw", enable = "avx512vl", enable = "pclmulqdq")]
    pub fn index_tape_seeded(data: &[u8], seed: u64, base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) -> u64 {
        let _ = seed;
        let mut offset = 0usize;
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let (mask, term) = unsafe { step(data.as_ptr().add(offset)) };
            push_tape(mask, term, base + offset as u32, seps, ends);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            let live = (1u64 << rem) - 1;
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let (mask, term) = unsafe { step(block.as_ptr()) };
            push_tape(mask & live, term & live, base + offset as u32, seps, ends);
        }
        0
    }

    /// Index the full 64-byte blocks of `data` (carries persist across
    /// calls); returns the number of bytes consumed. Streaming primitive.
    #[target_feature(enable = "avx512f", enable = "avx512bw", enable = "avx512vl", enable = "pclmulqdq")]
    pub fn index_tape_partial(data: &[u8], carries: &mut [u64; 0], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let _ = &carries;
        let mut offset = 0usize;
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len().
            let (mask, term) = unsafe { step(data.as_ptr().add(offset)) };
            push_tape(mask, term, base + offset as u32, seps, ends);
            offset += 64;
        }
    }

    /// Index one final zero-padded block (end-of-stream only); `live`
    /// masks off the padding bits.
    #[target_feature(enable = "avx512f", enable = "avx512bw", enable = "avx512vl", enable = "pclmulqdq")]
    pub fn index_tape_block(block: &[u8; 64], live: u64, carries: &mut [u64; 0], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let _ = &carries;
        // SAFETY: block is a readable 64-byte buffer.
        let (mask, term) = unsafe { step(block.as_ptr()) };
        push_tape(mask & live, term & live, base, seps, ends);
    }

    /// Fused FASTQ stats driver: newline masks come from the generated
    /// line-kernel step and feed the FASTQ validation/stat sink directly.
    #[target_feature(enable = "avx512f", enable = "avx512bw", enable = "avx512vl", enable = "pclmulqdq")]
    pub fn fastq_blocks(data: &[u8], sink: &mut super::FastqSink) -> Result<(), super::FastqError> {
        // SAFETY: __m512i and [u64; 8] are both 64-byte vector storage here.
        let mut checksum_acc: __m512i = unsafe {
            std::mem::transmute::<[u64; 8], __m512i>(sink.checksum_lanes)
        };

        let mut offset = 0usize;
        while offset + 128 <= data.len() {
            // SAFETY: offset + 128 <= data.len(), so both blocks are readable.
            let (m0, _) = unsafe { step(data.as_ptr().add(offset)) };
            let (m1, _) = unsafe { step(data.as_ptr().add(offset + 64)) };
            let error = unsafe { sink.drive_pair_avx512(data, m0, m1, offset, &mut checksum_acc) };
            if error != 0 {
                return Err(sink.take_error(error));
            }
            offset += 128;
        }
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let (mask, _) = unsafe { step(data.as_ptr().add(offset)) };
            let error = unsafe { sink.drive_avx512(data, mask, offset, &mut checksum_acc) };
            if error != 0 {
                return Err(sink.take_error(error));
            }
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            let live = (1u64 << rem) - 1;
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let (mask, _) = unsafe { step(block.as_ptr()) };
            let error = unsafe { sink.drive_avx512(data, mask & live, offset, &mut checksum_acc) };
            if error != 0 {
                return Err(sink.take_error(error));
            }
        }
        // SAFETY: __m512i and [u64; 8] are both 64-byte vector storage here.
        sink.checksum_lanes = unsafe { std::mem::transmute::<__m512i, [u64; 8]>(checksum_acc) };
        Ok(())
    }


    #[target_feature(enable = "avx512f", enable = "avx512bw", enable = "avx512vl", enable = "pclmulqdq")]
    unsafe fn step(ptr: *const u8) -> (u64, u64) {
        // SAFETY: caller guarantees 64 readable bytes at `ptr`.
        let (lo, hi) = unsafe {
            (
                _mm256_loadu_si256(ptr as *const __m256i),
                _mm256_loadu_si256(ptr.add(32) as *const __m256i),
            )
        };
        let v0 = eq_mask(lo, hi, 10u8); // class "\n"
        (v0, v0)
    }

    #[target_feature(enable = "avx512f", enable = "avx512bw", enable = "avx512vl")]
    fn eq_mask(lo: __m256i, hi: __m256i, byte: u8) -> u64 {
        let needle = _mm256_set1_epi8(byte as i8);
        let lo_bits = _mm256_cmpeq_epi8_mask(lo, needle) as u64;
        let hi_bits = _mm256_cmpeq_epi8_mask(hi, needle) as u64;
        lo_bits | (hi_bits << 32)
    }

    /// Branchless bit decoding (simdjson flatten_bits): write indexes in
    /// unconditional chunks of 8, then expose only the popcount-many real
    /// entries.
    #[inline]
    fn push_indexes(mut mask: u64, base: u32, out: &mut Vec<u32>) {
        let count = mask.count_ones() as usize;
        if count == 0 {
            return;
        }
        let len = out.len();
        out.reserve(count + 8);
        // SAFETY: capacity covers len + count + 8; chunked writes overshoot
        // by at most 7 entries and set_len exposes only the real ones.
        unsafe {
            let mut ptr = out.as_mut_ptr().add(len);
            let mut remaining = count as isize;
            while remaining > 0 {
                let mut j = 0;
                while j < 8 {
                    *ptr.add(j) = base + mask.trailing_zeros();
                    mask &= mask.wrapping_sub(1);
                    j += 1;
                }
                ptr = ptr.add(8);
                remaining -= 8;
            }
            out.set_len(len + count);
        }
    }
}

#[cfg(target_arch = "x86_64")]
mod avx2 {
    use std::arch::x86_64::*;

    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {
        let mut offset = 0usize;
        // Two blocks per iteration: amortizes loop control and lets the
        // second block's classification overlap the first block's extract.
        while offset + 128 <= data.len() {
            // SAFETY: offset + 128 <= data.len(), so both blocks are readable.
            let m0 = unsafe { step(data.as_ptr().add(offset)) }.0;
            push_indexes(m0, offset as u32, out);
            let m1 = unsafe { step(data.as_ptr().add(offset + 64)) }.0;
            push_indexes(m1, (offset + 64) as u32, out);
            offset += 128;
        }
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let mask = unsafe { step(data.as_ptr().add(offset)) }.0;
            push_indexes(mask, offset as u32, out);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let mask = unsafe { step(block.as_ptr()) }.0 & ((1u64 << rem) - 1);
            push_indexes(mask, offset as u32, out);
        }
    }


    /// Record-aware indexing; structural and terminator masks encode the tape.
    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_tape(data: &[u8], seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let mut offset = 0usize;
        // Two blocks per iteration (see index_structurals).
        while offset + 128 <= data.len() {
            // SAFETY: offset + 128 <= data.len(), so both blocks are readable.
            let (m0, t0) = unsafe { step(data.as_ptr().add(offset)) };
            push_tape(m0, t0, offset as u32, seps, ends);
            let (m1, t1) = unsafe { step(data.as_ptr().add(offset + 64)) };
            push_tape(m1, t1, (offset + 64) as u32, seps, ends);
            offset += 128;
        }
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let (mask, term) = unsafe { step(data.as_ptr().add(offset)) };
            push_tape(mask, term, offset as u32, seps, ends);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            let live = (1u64 << rem) - 1;
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let (mask, term) = unsafe { step(block.as_ptr()) };
            push_tape(mask & live, term & live, offset as u32, seps, ends);
        }
    }

    fn push_tape(structural: u64, term: u64, base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let sep_mask = structural & !term;
        let base_count = seps.len() as u64;
        push_indexes(sep_mask, base, seps);
        let mut t = term;
        while t != 0 {
            let idx = t.trailing_zeros();
            let below = (sep_mask & ((1u64 << idx) - 1)).count_ones() as u64;
            ends.push(((base_count + below) << 32) | (base + idx) as u64);
            t &= t - 1;
        }
    }

    /// Like `index_structurals` but seeded with the entry quote-parity carry
    /// and an absolute base offset; returns the *final* carry so the parallel
    /// driver can recover each chunk's quote parity without a counting prepass.
    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_structurals_seeded(data: &[u8], seed: u64, base: u32, out: &mut Vec<u32>) -> u64 {
        let _ = seed;
        let mut offset = 0usize;
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len().
            let mask = unsafe { step(data.as_ptr().add(offset)) }.0;
            push_indexes(mask, base + offset as u32, out);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let mask = unsafe { step(block.as_ptr()) }.0 & ((1u64 << rem) - 1);
            push_indexes(mask, base + offset as u32, out);
        }
        0
    }

    /// Seeded-carry, based variant of `index_tape` for parallel parsing.
    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_tape_seeded(data: &[u8], seed: u64, base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) -> u64 {
        let _ = seed;
        let mut offset = 0usize;
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let (mask, term) = unsafe { step(data.as_ptr().add(offset)) };
            push_tape(mask, term, base + offset as u32, seps, ends);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            let live = (1u64 << rem) - 1;
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let (mask, term) = unsafe { step(block.as_ptr()) };
            push_tape(mask & live, term & live, base + offset as u32, seps, ends);
        }
        0
    }

    /// Index the full 64-byte blocks of `data` (carries persist across
    /// calls); returns the number of bytes consumed. Streaming primitive.
    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_tape_partial(data: &[u8], carries: &mut [u64; 0], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let _ = &carries;
        let mut offset = 0usize;
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len().
            let (mask, term) = unsafe { step(data.as_ptr().add(offset)) };
            push_tape(mask, term, base + offset as u32, seps, ends);
            offset += 64;
        }
    }

    /// Index one final zero-padded block (end-of-stream only); `live`
    /// masks off the padding bits.
    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_tape_block(block: &[u8; 64], live: u64, carries: &mut [u64; 0], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let _ = &carries;
        // SAFETY: block is a readable 64-byte buffer.
        let (mask, term) = unsafe { step(block.as_ptr()) };
        push_tape(mask & live, term & live, base, seps, ends);
    }

    /// Fused FASTQ stats driver: newline masks come from the generated
    /// line-kernel step and feed the FASTQ validation/stat sink directly.
    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn fastq_blocks(data: &[u8], sink: &mut super::FastqSink) -> Result<(), super::FastqError> {
        // SAFETY: __m256i and [u64; 4] are both 32-byte vector storage here.
        let mut checksum_acc: __m256i = unsafe {
            std::mem::transmute::<[u64; 4], __m256i>([
                sink.checksum_lanes[0],
                sink.checksum_lanes[1],
                sink.checksum_lanes[2],
                sink.checksum_lanes[3],
            ])
        };

        let mut offset = 0usize;
        while offset + 128 <= data.len() {
            // SAFETY: offset + 128 <= data.len(), so both blocks are readable.
            let (m0, _) = unsafe { step(data.as_ptr().add(offset)) };
            let (m1, _) = unsafe { step(data.as_ptr().add(offset + 64)) };
            let error = unsafe { sink.drive_pair_avx2(data, m0, m1, offset, &mut checksum_acc) };
            if error != 0 {
                return Err(sink.take_error(error));
            }
            offset += 128;
        }
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let (mask, _) = unsafe { step(data.as_ptr().add(offset)) };
            let error = unsafe { sink.drive_avx2(data, mask, offset, &mut checksum_acc) };
            if error != 0 {
                return Err(sink.take_error(error));
            }
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            let live = (1u64 << rem) - 1;
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let (mask, _) = unsafe { step(block.as_ptr()) };
            let error = unsafe { sink.drive_avx2(data, mask & live, offset, &mut checksum_acc) };
            if error != 0 {
                return Err(sink.take_error(error));
            }
        }
        // SAFETY: __m256i and [u64; 4] are both 32-byte vector storage here.
        let checksum_lanes: [u64; 4] = unsafe {
            std::mem::transmute::<__m256i, [u64; 4]>(checksum_acc)
        };
        sink.checksum_lanes[..4].copy_from_slice(&checksum_lanes);
        Ok(())
    }


    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    unsafe fn step(ptr: *const u8) -> (u64, u64) {
        // SAFETY: caller guarantees 64 readable bytes at `ptr`.
        let (lo, hi) = unsafe {
            (
                _mm256_loadu_si256(ptr as *const __m256i),
                _mm256_loadu_si256(ptr.add(32) as *const __m256i),
            )
        };
        let v0 = eq_mask(lo, hi, 10u8); // class "\n"
        (v0, v0)
    }

    #[target_feature(enable = "avx2")]
    fn eq_mask(lo: __m256i, hi: __m256i, byte: u8) -> u64 {
        let needle = _mm256_set1_epi8(byte as i8);
        let lo_bits = _mm256_movemask_epi8(_mm256_cmpeq_epi8(lo, needle)) as u32 as u64;
        let hi_bits = _mm256_movemask_epi8(_mm256_cmpeq_epi8(hi, needle)) as u32 as u64;
        lo_bits | (hi_bits << 32)
    }

    /// Branchless bit decoding (simdjson flatten_bits): write indexes in
    /// unconditional chunks of 8, then expose only the popcount-many real
    /// entries.
    #[inline]
    fn push_indexes(mut mask: u64, base: u32, out: &mut Vec<u32>) {
        let count = mask.count_ones() as usize;
        if count == 0 {
            return;
        }
        let len = out.len();
        out.reserve(count + 8);
        // SAFETY: capacity covers len + count + 8; chunked writes overshoot
        // by at most 7 entries and set_len exposes only the real ones.
        unsafe {
            let mut ptr = out.as_mut_ptr().add(len);
            let mut remaining = count as isize;
            while remaining > 0 {
                let mut j = 0;
                while j < 8 {
                    *ptr.add(j) = base + mask.trailing_zeros();
                    mask &= mask.wrapping_sub(1);
                    j += 1;
                }
                ptr = ptr.add(8);
                remaining -= 8;
            }
            out.set_len(len + count);
        }
    }
}

}

pub use self::generated::*;
