// Generated by falx from format `json`. Do not edit by hand;
// regenerate with `cargo run --example generate` (in-tree) or the falx CLI.
//
// Structural indexer: appends to `out` the byte offset of every set bit in
// the format's output bitstream (its structural positions). Self-contained:
// depends only on std.
//
// Also exposes a span API: `parse(data)` -> `records()` -> `field(i)`,
// with dialect-aware quote stripping and escape resolution.

/// Stream-start carry values; kernels and the stream parser all
/// begin from this state.
const CARRY_INIT: [u64; 4] = [0, 0, 0, 0];

/// Index the structural positions of `data` into `out`.
pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx2::index_structurals(data, out) };
        return;
    }
    fallback::index_structurals(data, out);
}

/// Record-aware tape indexing used by [`parse`].
fn index_tape(data: &[u8], seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx2::index_tape(data, seps, ends) };
        return;
    }
    fallback::index_tape(data, seps, ends);
}

/// Index `data` and return a lazy record/field view over it.
pub fn parse(data: &[u8]) -> Parsed<'_> {
    let mut seps = Vec::with_capacity(data.len() / 16 + 8);
    let mut ends = Vec::with_capacity(data.len() / 32 + 8);
    index_tape(data, &mut seps, &mut ends);
    Parsed { data, seps, ends }
}

/// A structural tape over borrowed input: separator positions plus record
/// ends carrying cumulative separator counts, so record iteration is O(1)
/// per record and never rescans the input.
pub struct Parsed<'a> {
    data: &'a [u8],
    seps: Vec<u32>,
    ends: Vec<u64>,
}

impl<'a> Parsed<'a> {
    /// Iterate records (lines outside quoted regions). A record's trailing
    /// `\r` is trimmed; an empty line yields a record with one empty field.
    pub fn records(&self) -> Records<'_> {
        self.records_range(0..self.ends.len())
    }

    /// Number of newline-terminated records (a trailing unterminated record
    /// is not counted but is still yielded by iteration).
    pub fn terminated_record_count(&self) -> usize {
        self.ends.len()
    }

    /// Iterate a sub-range of terminated records. Disjoint ranges cover
    /// disjoint input and can be walked from different threads — the
    /// building block for parallel record processing. The range ending at
    /// `terminated_record_count()` also yields any trailing unterminated
    /// record.
    pub fn records_range(&self, range: std::ops::Range<usize>) -> Records<'_> {
        let (byte_pos, sep_pos) = if range.start == 0 {
            (0, 0)
        } else {
            let prev = self.ends[range.start - 1];
            ((prev & 0xFFFF_FFFF) as usize + 1, (prev >> 32) as usize)
        };
        let data_end = if range.start >= range.end && !self.ends.is_empty() {
            byte_pos // empty sub-range: fence immediately, yield nothing
        } else if range.end == self.ends.len() {
            self.data.len()
        } else {
            // Coverage fence: the byte after this chunk's last terminator.
            (self.ends[range.end - 1] & 0xFFFF_FFFF) as usize + 1
        };
        Records {
            data: self.data,
            seps: &self.seps,
            ends: &self.ends[..range.end],
            next_end: range.start,
            byte_pos,
            sep_pos,
            data_end,
        }
    }
}

pub struct Records<'p> {
    data: &'p [u8],
    seps: &'p [u32],
    ends: &'p [u64],
    next_end: usize,
    byte_pos: usize,
    sep_pos: usize,
    /// Trailing-record fence: iteration past the last tape entry stops here.
    data_end: usize,
}

impl<'p> Records<'p> {
    /// Produce the next record in tape order, comment lines included.
    fn next_raw(&mut self) -> Option<Record<'p>> {
        let start = self.byte_pos;
        let (end, seps) = if self.next_end < self.ends.len() {
            let entry = self.ends[self.next_end];
            self.next_end += 1;
            let end = (entry & 0xFFFF_FFFF) as usize;
            let cum = (entry >> 32) as usize;
            let seps = &self.seps[self.sep_pos..cum];
            self.sep_pos = cum;
            self.byte_pos = end + 1;
            (end, seps)
        } else {
            // Trailing record without a newline (only at the true data end).
            if start >= self.data_end {
                return None;
            }
            let seps = &self.seps[self.sep_pos..];
            self.sep_pos = self.seps.len();
            self.byte_pos = self.data_end;
            (self.data_end, seps)
        };
        Some(Record { data: self.data, start, end, seps })
    }
}

impl<'p> Iterator for Records<'p> {
    type Item = Record<'p>;

    fn next(&mut self) -> Option<Record<'p>> {
        self.next_raw()
    }
}

/// One record: a span of input plus the separator positions inside it.
/// The `\r` of a `\r\n` terminator is trimmed lazily, where bytes are
/// actually read, so tape-only walks never touch the input buffer.
#[derive(Clone, Copy)]
pub struct Record<'p> {
    data: &'p [u8],
    start: usize,
    end: usize,
    seps: &'p [u32],
}

impl<'p> Record<'p> {
    /// Record end with a trailing `\r` (of `\r\n`) trimmed.
    #[inline]
    fn trimmed_end(&self) -> usize {
        if self.end > self.start && self.data[self.end - 1] == b'\r' {
            self.end - 1
        } else {
            self.end
        }
    }

    /// The whole record span, terminator excluded.
    pub fn as_bytes(&self) -> &'p [u8] {
        &self.data[self.start..self.trimmed_end()]
    }

    pub fn field_count(&self) -> usize {
        self.seps.len() + 1
    }

    /// Byte-offset span `(from, to)` of field `i`, quotes and escapes
    /// intact; offsets index the buffer the tape was built over.
    pub fn field_span(&self, i: usize) -> Option<(u32, u32)> {
        if i > self.seps.len() {
            return None;
        }
        let from = if i == 0 {
            self.start
        } else {
            self.seps[i - 1] as usize + 1
        };
        let to = if i == self.seps.len() {
            self.trimmed_end()
        } else {
            self.seps[i] as usize
        };
        Some((from as u32, to as u32))
    }

    /// Raw span of field `i`: quotes and escapes intact.
    pub fn field_raw(&self, i: usize) -> Option<&'p [u8]> {
        self.field_span(i)
            .map(|(from, to)| &self.data[from as usize..to as usize])
    }

    /// Field `i` with surrounding quotes stripped and escapes resolved;
    /// borrows unless an escape sequence forces a copy.
    pub fn field(&self, i: usize) -> Option<std::borrow::Cow<'p, [u8]>> {
        self.field_raw(i).map(clean)
    }

    pub fn fields(&self) -> Fields<'p> {
        Fields {
            data: self.data,
            seps: self.seps,
            next_sep: 0,
            from: self.start,
            end: self.trimmed_end(),
            done: false,
        }
    }
}

/// Field iterator: one running offset, one separator-slice cursor — no
/// per-field bounds re-derivation.
pub struct Fields<'p> {
    data: &'p [u8],
    seps: &'p [u32],
    next_sep: usize,
    from: usize,
    end: usize,
    done: bool,
}

impl<'p> Iterator for Fields<'p> {
    type Item = std::borrow::Cow<'p, [u8]>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.next_sep < self.seps.len() {
            let to = self.seps[self.next_sep] as usize;
            self.next_sep += 1;
            let span = &self.data[self.from..to];
            self.from = to + 1;
            Some(clean(span))
        } else if !self.done {
            self.done = true;
            Some(clean(&self.data[self.from..self.end]))
        } else {
            None
        }
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let n = self.seps.len() - self.next_sep + (!self.done) as usize;
        (n, Some(n))
    }
}

/// Incremental parser for unbounded input: feed chunks, receive complete
/// records via callback. Kernel carries persist across feeds, so quoted
/// regions and escape runs spanning chunk boundaries are handled exactly.
/// Bytes of the unfinished trailing record are buffered internally and
/// compacted amortized; a single record must fit in memory (< 4 GiB).
pub struct StreamParser {
    buf: Vec<u8>,
    seps: Vec<u32>,
    ends: Vec<u64>,
    indexed: usize,
    emitted: usize,
    emitted_seps: usize,
    record_start: usize,
    carries: [u64; 4],
}

/// Create a [`StreamParser`].
pub fn stream() -> StreamParser {
    StreamParser {
        buf: Vec::new(),
        seps: Vec::new(),
        ends: Vec::new(),
        indexed: 0,
        emitted: 0,
        emitted_seps: 0,
        record_start: 0,
        carries: CARRY_INIT,
    }
}

impl StreamParser {
    /// Feed the next chunk; `on_record` is called once per record completed
    /// by this chunk.
    pub fn feed(&mut self, chunk: &[u8], mut on_record: impl FnMut(Record<'_>)) {
        self.buf.extend_from_slice(chunk);
        index_tape_partial_dispatch(
            &self.buf[self.indexed..],
            &mut self.carries,
            self.indexed as u32,
            &mut self.seps,
            &mut self.ends,
        );
        self.indexed += (self.buf.len() - self.indexed) & !63;
        self.emit_ready(&mut on_record);
        self.compact();
    }

    /// Signal end of input; emits any records completed by the final
    /// partial block plus a trailing unterminated record.
    pub fn finish(mut self, mut on_record: impl FnMut(Record<'_>)) {
        let rem = self.buf.len() - self.indexed;
        if rem > 0 {
            // True end of stream: zero padding is safe here, exactly as in
            // the batch tail.
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&self.buf[self.indexed..]);
            let live = (1u64 << rem) - 1;
            index_tape_block_dispatch(
                &block,
                live,
                &mut self.carries,
                self.indexed as u32,
                &mut self.seps,
                &mut self.ends,
            );
        }
        self.emit_ready(&mut on_record);
        if self.record_start < self.buf.len() {
            on_record(Record {
                data: &self.buf,
                start: self.record_start,
                end: self.buf.len(),
                seps: &self.seps[self.emitted_seps..],
            });
        }
    }

    fn emit_ready(&mut self, on_record: &mut impl FnMut(Record<'_>)) {
        while self.emitted < self.ends.len() {
            let entry = self.ends[self.emitted];
            let end = (entry & 0xFFFF_FFFF) as usize;
            let cum = (entry >> 32) as usize;
            on_record(Record {
                data: &self.buf,
                start: self.record_start,
                end,
                seps: &self.seps[self.emitted_seps..cum],
            });
            self.record_start = end + 1;
            self.emitted_seps = cum;
            self.emitted += 1;
        }
    }

    /// Drop consumed bytes/tape once they dominate the buffer. The cut is
    /// 64-byte aligned: it keeps block boundaries and, critically, byte
    /// position parity stable (the escape machinery's even/odd constant
    /// masks are parity-dependent).
    fn compact(&mut self) {
        let base = self.record_start.min(self.indexed) & !63;
        if base < 4096 || base < self.buf.len() / 2 {
            return;
        }
        self.buf.copy_within(base.., 0);
        self.buf.truncate(self.buf.len() - base);
        self.indexed -= base;
        self.seps.drain(..self.emitted_seps);
        for p in &mut self.seps {
            *p -= base as u32;
        }
        let rebase = ((self.emitted_seps as u64) << 32) | base as u64;
        self.ends.drain(..self.emitted);
        for e in &mut self.ends {
            *e -= rebase;
        }
        self.record_start -= base;
        self.emitted = 0;
        self.emitted_seps = 0;
    }
}

fn index_tape_partial_dispatch(data: &[u8], carries: &mut [u64; 4], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx2::index_tape_partial(data, carries, base, seps, ends) };
        return;
    }
    fallback::index_tape_partial(data, carries, base, seps, ends);
}

fn index_tape_block_dispatch(block: &[u8; 64], live: u64, carries: &mut [u64; 4], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx2::index_tape_block(block, live, carries, base, seps, ends) };
        return;
    }
    fallback::index_tape_block(block, live, carries, base, seps, ends);
}

/// Strip surrounding quotes and resolve backslash escapes (`\x` -> `x`).
fn clean(raw: &[u8]) -> std::borrow::Cow<'_, [u8]> {
    const Q: u8 = 34u8;
    const E: u8 = 92u8;
    let body = if raw.len() >= 2 && raw[0] == Q && raw[raw.len() - 1] == Q {
        &raw[1..raw.len() - 1]
    } else {
        raw
    };
    if !body.contains(&E) {
        return std::borrow::Cow::Borrowed(body);
    }
    let mut out = Vec::with_capacity(body.len());
    let mut i = 0;
    while i < body.len() {
        if body[i] == E && i + 1 < body.len() {
            out.push(body[i + 1]);
            i += 2;
        } else {
            out.push(body[i]);
            i += 1;
        }
    }
    std::borrow::Cow::Owned(out)
}

/// How bracket matching failed. Positions are byte offsets into the input.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NestError {
    /// A close bracket with no matching open, or closing the wrong kind.
    UnmatchedClose(u32),
    /// Input ended with brackets still open; the innermost open's position.
    UnclosedOpen(u32),
}

/// The nested structural tape over borrowed input: one `u64` entry per
/// structural byte. The low 32 bits are the byte position; for bracket
/// entries the high 32 bits are the tape index of the matching partner
/// (`u32::MAX` while unclosed), making container skips O(1). Separator
/// entries leave the high bits zero and are classified by re-reading the
/// input byte, never by the partner field.
pub struct Nested<'a> {
    data: &'a [u8],
    tape: Vec<u64>,
    /// First bracket-matching error. Tape building stops at an unmatched
    /// close; navigation over an errored tape is best-effort, never panics.
    pub error: Option<NestError>,
}

/// Index `data` and match nesting brackets into a navigable tape.
/// Brackets inside quoted regions are inert and never reach the tape.
pub fn parse_nested(data: &[u8]) -> Nested<'_> {
    let mut idx = Vec::new();
    index_structurals(data, &mut idx);
    let mut tape: Vec<u64> = Vec::with_capacity(idx.len());
    let mut stack: Vec<u32> = Vec::new();
    let mut error = None;
    for &pos in &idx {
        match data[pos as usize] {
            b'{' | b'[' => {
                stack.push(tape.len() as u32);
                tape.push(((u32::MAX as u64) << 32) | pos as u64);
            }
            b @ (b'}' | b']') => {
                let open = match stack.pop() {
                    Some(i) if close_of((tape[i as usize] as u32) as usize, data) == b => i,
                    _ => {
                        error = Some(NestError::UnmatchedClose(pos));
                        break;
                    }
                };
                let close = tape.len() as u32;
                tape[open as usize] = ((close as u64) << 32) | (tape[open as usize] as u32) as u64;
                tape.push(((open as u64) << 32) | pos as u64);
            }
            _ => tape.push(pos as u64),
        }
    }
    // Edition-agnostic single condition: generated files compile under the
    // consumer's edition, so no let-chains.
    if let (None, Some(&innermost)) = (error, stack.last()) {
        error = Some(NestError::UnclosedOpen(tape[innermost as usize] as u32));
    }
    Nested { data, tape, error }
}

/// The close byte that matches the open bracket at `pos`. Returns 0 for a
/// non-open byte, which can never equal a close byte that reaches the
/// caller's comparison, so a corrupt position degrades to a match failure.
fn close_of(pos: usize, data: &[u8]) -> u8 {
    match data[pos] {
        b'{' => b'}',
        b'[' => b']',
        _ => 0,
    }
}

/// Trim ASCII whitespace from both ends of `data[start..end]`, as offsets.
fn trim_ws(data: &[u8], mut start: usize, mut end: usize) -> (usize, usize) {
    while start < end && matches!(data[start], b' ' | b'\t' | b'\r' | b'\n') {
        start += 1;
    }
    while end > start && matches!(data[end - 1], b' ' | b'\t' | b'\r' | b'\n') {
        end -= 1;
    }
    (start, end)
}

impl<'a> Nested<'a> {
    /// Raw tape access; see the type docs for the entry layout.
    pub fn tape(&self) -> &[u64] {
        &self.tape
    }

    /// The top-level items: every bracketed container and every
    /// non-whitespace scalar run between top-level structural bytes.
    pub fn items(&self) -> Items<'a, '_> {
        Items {
            nested: self,
            next: 0,
            end: self.tape.len(),
            cursor: 0,
            limit: self.data.len(),
        }
    }
}

/// One value: a bracketed container or a whitespace-trimmed scalar span.
#[derive(Clone, Copy)]
pub struct Node<'a, 'p> {
    nested: &'p Nested<'a>,
    repr: Repr,
}

#[derive(Clone, Copy)]
enum Repr {
    /// Tape index of the opening bracket.
    Container(usize),
    /// Trimmed byte span.
    Scalar(usize, usize),
}

impl<'a, 'p> Node<'a, 'p> {
    /// The container's opening bracket byte; `None` for scalars.
    pub fn open(&self) -> Option<u8> {
        match self.repr {
            Repr::Container(i) => {
                Some(self.nested.data[(self.nested.tape[i] as u32) as usize])
            }
            Repr::Scalar(..) => None,
        }
    }

    /// The full input span: brackets included for containers, trimmed bytes
    /// for scalars (quotes and escapes intact — spans are zero-copy).
    pub fn bytes(&self) -> &'a [u8] {
        match self.repr {
            Repr::Container(i) => {
                let entry = self.nested.tape[i];
                let start = (entry as u32) as usize;
                let close = (entry >> 32) as u32;
                let end = if close == u32::MAX {
                    self.nested.data.len()
                } else {
                    (self.nested.tape[close as usize] as u32) as usize + 1
                };
                &self.nested.data[start..end]
            }
            Repr::Scalar(start, end) => &self.nested.data[start..end],
        }
    }

    /// The container's items in input order; empty for scalars. Every
    /// separator byte splits items, so formats that separate keys from
    /// values with a second separator (JSON objects' `:`) yield keys and
    /// values as consecutive items.
    pub fn items(&self) -> Items<'a, 'p> {
        match self.repr {
            Repr::Container(i) => {
                let entry = self.nested.tape[i];
                let close = (entry >> 32) as u32;
                let (end, limit) = if close == u32::MAX {
                    (self.nested.tape.len(), self.nested.data.len())
                } else {
                    (
                        close as usize,
                        (self.nested.tape[close as usize] as u32) as usize,
                    )
                };
                Items {
                    nested: self.nested,
                    next: i + 1,
                    end,
                    cursor: (entry as u32) as usize + 1,
                    limit,
                }
            }
            Repr::Scalar(..) => Items {
                nested: self.nested,
                next: 0,
                end: 0,
                cursor: 0,
                limit: 0,
            },
        }
    }
}

/// Iterator over the items of one nesting level.
pub struct Items<'a, 'p> {
    nested: &'p Nested<'a>,
    /// Next tape index to inspect; `end` is this level's exclusive bound.
    next: usize,
    end: usize,
    /// Byte position where the pending scalar gap starts.
    cursor: usize,
    /// Byte end of this level's contents.
    limit: usize,
}

impl<'a, 'p> Iterator for Items<'a, 'p> {
    type Item = Node<'a, 'p>;

    fn next(&mut self) -> Option<Node<'a, 'p>> {
        loop {
            if self.next >= self.end {
                let (s, e) = trim_ws(self.nested.data, self.cursor, self.limit);
                self.cursor = self.limit;
                if s < e {
                    return Some(Node { nested: self.nested, repr: Repr::Scalar(s, e) });
                }
                return None;
            }
            let entry = self.nested.tape[self.next];
            let pos = (entry as u32) as usize;
            match self.nested.data[pos] {
                b'{' | b'[' => {
                    // A pending scalar gap is yielded before the bracket
                    // (well-formed input always separates siblings, so the
                    // gap is normally whitespace).
                    let (s, e) = trim_ws(self.nested.data, self.cursor, pos);
                    if s < e {
                        self.cursor = pos;
                        return Some(Node { nested: self.nested, repr: Repr::Scalar(s, e) });
                    }
                    let node = Node { nested: self.nested, repr: Repr::Container(self.next) };
                    let close = (entry >> 32) as u32;
                    if close == u32::MAX || close as usize >= self.end {
                        // Unclosed (errored tape): the container swallows
                        // the rest of this level.
                        self.next = self.end;
                        self.cursor = self.limit;
                    } else {
                        self.next = close as usize + 1;
                        self.cursor = (self.nested.tape[close as usize] as u32) as usize + 1;
                    }
                    return Some(node);
                }
                _ => {
                    self.next += 1;
                    let (s, e) = trim_ws(self.nested.data, self.cursor, pos);
                    self.cursor = pos + 1;
                    if s < e {
                        return Some(Node { nested: self.nested, repr: Repr::Scalar(s, e) });
                    }
                }
            }
        }
    }
}

/// Portable kernel, public so the dispatch-bypassed path stays testable.
pub mod fallback {
    pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {
        let mut carries = super::CARRY_INIT;
        let mut offset = 0usize;
        while offset + 64 <= data.len() {
            let block: &[u8; 64] = data[offset..offset + 64].try_into().unwrap();
            let mask = step(block, &mut carries).0;
            push_indexes(mask, offset as u32, out);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            // Mask off bits that fall in the zero padding.
            let mask = step(&block, &mut carries).0 & ((1u64 << rem) - 1);
            push_indexes(mask, offset as u32, out);
        }
    }

    /// Record-aware indexing for [`crate::parse`]-style use: separator
    /// positions into `seps`, record ends into `ends` encoded as
    /// (cumulative separator count << 32) | byte position.
    pub fn index_tape(data: &[u8], seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let mut carries = super::CARRY_INIT;
        let mut offset = 0usize;
        while offset + 64 <= data.len() {
            let block: &[u8; 64] = data[offset..offset + 64].try_into().unwrap();
            let (mask, term) = step(block, &mut carries);
            push_tape(mask, term, offset as u32, seps, ends);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            let live = (1u64 << rem) - 1;
            let (mask, term) = step(&block, &mut carries);
            push_tape(mask & live, term & live, offset as u32, seps, ends);
        }
    }

    fn push_tape(structural: u64, term: u64, base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let sep_mask = structural & !term;
        let base_count = seps.len() as u64;
        push_indexes(sep_mask, base, seps);
        let mut t = term;
        while t != 0 {
            let idx = t.trailing_zeros();
            let below = (sep_mask & ((1u64 << idx) - 1)).count_ones() as u64;
            ends.push(((base_count + below) << 32) | (base + idx) as u64);
            t &= t - 1;
        }
    }

    /// Index the full 64-byte blocks of `data` (carries persist across
    /// calls); returns the number of bytes consumed. Streaming primitive.
    pub fn index_tape_partial(data: &[u8], carries: &mut [u64; 4], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let _ = &carries;
        let mut offset = 0usize;
        while offset + 64 <= data.len() {
            let block: &[u8; 64] = data[offset..offset + 64].try_into().unwrap();
            let (mask, term) = step(block, carries);
            push_tape(mask, term, base + offset as u32, seps, ends);
            offset += 64;
        }
    }

    /// Index one final zero-padded block (end-of-stream only); `live`
    /// masks off the padding bits.
    pub fn index_tape_block(block: &[u8; 64], live: u64, carries: &mut [u64; 4], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let _ = &carries;
        let (mask, term) = step(block, carries);
        push_tape(mask & live, term & live, base, seps, ends);
    }

    #[inline]
    fn step(block: &[u8; 64], carries: &mut [u64; 4]) -> (u64, u64) {
        let v0 = eq_mask(block, 10u8); // class "\n"
        let v1 = eq_mask(block, 44u8) | eq_mask(block, 58u8) | eq_mask(block, 91u8) | eq_mask(block, 93u8) | eq_mask(block, 123u8) | eq_mask(block, 125u8); // class ",:[]{}"
        let v2 = eq_mask(block, 34u8); // class "\""
        let v3 = eq_mask(block, 92u8); // class "\\"
        let v4 = { let shifted = (v3 << 1) | carries[0]; carries[0] = v3 >> 63; shifted };
        let v5 = !v4;
        let v6 = v3 & v5;
        let v7 = 0x5555555555555555u64;
        let v8 = 0xaaaaaaaaaaaaaaaau64;
        let v9 = !v3;
        let v10 = v6 & v7;
        let v11 = { let (partial, c1) = v3.overflowing_add(v10); let (sum, c2) = partial.overflowing_add(carries[1]); carries[1] = (c1 | c2) as u64; sum };
        let v12 = v11 & v9;
        let v13 = v12 & v8;
        let v14 = v6 & v8;
        let v15 = { let (partial, c1) = v3.overflowing_add(v14); let (sum, c2) = partial.overflowing_add(carries[2]); carries[2] = (c1 | c2) as u64; sum };
        let v16 = v15 & v9;
        let v17 = v16 & v7;
        let v18 = v13 | v17;
        let v19 = !v18;
        let v20 = v2 & v19;
        let v21 = { let parity = prefix_xor(v20) ^ carries[3]; carries[3] = ((parity as i64) >> 63) as u64; parity };
        let v22 = !v21;
        let v23 = v1 & v22;
        (v23, v23 & v0)
    }

    #[inline]
    fn eq_mask(block: &[u8; 64], byte: u8) -> u64 {
        let mut mask = 0u64;
        let mut i = 0;
        while i < 64 {
            mask |= ((block[i] == byte) as u64) << i;
            i += 1;
        }
        mask
    }

    #[inline]
    fn prefix_xor(mut x: u64) -> u64 {
        x ^= x << 1;
        x ^= x << 2;
        x ^= x << 4;
        x ^= x << 8;
        x ^= x << 16;
        x ^= x << 32;
        x
    }

    #[inline]
    fn push_indexes(mut mask: u64, base: u32, out: &mut Vec<u32>) {
        while mask != 0 {
            out.push(base + mask.trailing_zeros());
            mask &= mask - 1;
        }
    }
}

#[cfg(target_arch = "x86_64")]
mod avx2 {
    use std::arch::x86_64::*;

    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {
        let mut carries = super::CARRY_INIT;
        let mut offset = 0usize;
        // Two blocks per iteration: amortizes loop control and lets the
        // second block's classification overlap the first block's extract.
        while offset + 128 <= data.len() {
            // SAFETY: offset + 128 <= data.len(), so both blocks are readable.
            let m0 = unsafe { step(data.as_ptr().add(offset), &mut carries) }.0;
            push_indexes(m0, offset as u32, out);
            let m1 = unsafe { step(data.as_ptr().add(offset + 64), &mut carries) }.0;
            push_indexes(m1, (offset + 64) as u32, out);
            offset += 128;
        }
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let mask = unsafe { step(data.as_ptr().add(offset), &mut carries) }.0;
            push_indexes(mask, offset as u32, out);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let mask = unsafe { step(block.as_ptr(), &mut carries) }.0 & ((1u64 << rem) - 1);
            push_indexes(mask, offset as u32, out);
        }
    }


    /// Record-aware indexing; see the fallback twin for the tape encoding.
    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_tape(data: &[u8], seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let mut carries = super::CARRY_INIT;
        let mut offset = 0usize;
        // Two blocks per iteration (see index_structurals).
        while offset + 128 <= data.len() {
            // SAFETY: offset + 128 <= data.len(), so both blocks are readable.
            let (m0, t0) = unsafe { step(data.as_ptr().add(offset), &mut carries) };
            push_tape(m0, t0, offset as u32, seps, ends);
            let (m1, t1) = unsafe { step(data.as_ptr().add(offset + 64), &mut carries) };
            push_tape(m1, t1, (offset + 64) as u32, seps, ends);
            offset += 128;
        }
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let (mask, term) = unsafe { step(data.as_ptr().add(offset), &mut carries) };
            push_tape(mask, term, offset as u32, seps, ends);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            let live = (1u64 << rem) - 1;
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let (mask, term) = unsafe { step(block.as_ptr(), &mut carries) };
            push_tape(mask & live, term & live, offset as u32, seps, ends);
        }
    }

    fn push_tape(structural: u64, term: u64, base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let sep_mask = structural & !term;
        let base_count = seps.len() as u64;
        push_indexes(sep_mask, base, seps);
        let mut t = term;
        while t != 0 {
            let idx = t.trailing_zeros();
            let below = (sep_mask & ((1u64 << idx) - 1)).count_ones() as u64;
            ends.push(((base_count + below) << 32) | (base + idx) as u64);
            t &= t - 1;
        }
    }

    /// Index the full 64-byte blocks of `data` (carries persist across
    /// calls); returns the number of bytes consumed. Streaming primitive.
    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_tape_partial(data: &[u8], carries: &mut [u64; 4], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let _ = &carries;
        let mut offset = 0usize;
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len().
            let (mask, term) = unsafe { step(data.as_ptr().add(offset), carries) };
            push_tape(mask, term, base + offset as u32, seps, ends);
            offset += 64;
        }
    }

    /// Index one final zero-padded block (end-of-stream only); `live`
    /// masks off the padding bits.
    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_tape_block(block: &[u8; 64], live: u64, carries: &mut [u64; 4], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let _ = &carries;
        // SAFETY: block is a readable 64-byte buffer.
        let (mask, term) = unsafe { step(block.as_ptr(), carries) };
        push_tape(mask & live, term & live, base, seps, ends);
    }

    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    unsafe fn step(ptr: *const u8, carries: &mut [u64; 4]) -> (u64, u64) {
        // SAFETY: caller guarantees 64 readable bytes at `ptr`.
        let (lo, hi) = unsafe {
            (
                _mm256_loadu_si256(ptr as *const __m256i),
                _mm256_loadu_si256(ptr.add(32) as *const __m256i),
            )
        };
        let v0 = eq_mask(lo, hi, 10u8); // class "\n"
        let v1 = eq_mask(lo, hi, 44u8) | eq_mask(lo, hi, 58u8) | eq_mask(lo, hi, 91u8) | eq_mask(lo, hi, 93u8) | eq_mask(lo, hi, 123u8) | eq_mask(lo, hi, 125u8); // class ",:[]{}"
        let v2 = eq_mask(lo, hi, 34u8); // class "\""
        let v3 = eq_mask(lo, hi, 92u8); // class "\\"
        let v4 = { let shifted = (v3 << 1) | carries[0]; carries[0] = v3 >> 63; shifted };
        let v5 = !v4;
        let v6 = v3 & v5;
        let v7 = 0x5555555555555555u64;
        let v8 = 0xaaaaaaaaaaaaaaaau64;
        let v9 = !v3;
        let v10 = v6 & v7;
        let v11 = { let (partial, c1) = v3.overflowing_add(v10); let (sum, c2) = partial.overflowing_add(carries[1]); carries[1] = (c1 | c2) as u64; sum };
        let v12 = v11 & v9;
        let v13 = v12 & v8;
        let v14 = v6 & v8;
        let v15 = { let (partial, c1) = v3.overflowing_add(v14); let (sum, c2) = partial.overflowing_add(carries[2]); carries[2] = (c1 | c2) as u64; sum };
        let v16 = v15 & v9;
        let v17 = v16 & v7;
        let v18 = v13 | v17;
        let v19 = !v18;
        let v20 = v2 & v19;
        let v21 = { let parity = prefix_xor(v20) ^ carries[3]; carries[3] = ((parity as i64) >> 63) as u64; parity };
        let v22 = !v21;
        let v23 = v1 & v22;
        (v23, v23 & v0)
    }

    #[target_feature(enable = "avx2")]
    fn eq_mask(lo: __m256i, hi: __m256i, byte: u8) -> u64 {
        let needle = _mm256_set1_epi8(byte as i8);
        let lo_bits = _mm256_movemask_epi8(_mm256_cmpeq_epi8(lo, needle)) as u32 as u64;
        let hi_bits = _mm256_movemask_epi8(_mm256_cmpeq_epi8(hi, needle)) as u32 as u64;
        lo_bits | (hi_bits << 32)
    }

    #[target_feature(enable = "pclmulqdq")]
    fn prefix_xor(mask: u64) -> u64 {
        let ones = _mm_set1_epi8(-1);
        let value = _mm_set_epi64x(0, mask as i64);
        let product = _mm_clmulepi64_si128::<0>(value, ones);
        _mm_cvtsi128_si64(product) as u64
    }

    /// Branchless bit decoding (simdjson flatten_bits): write indexes in
    /// unconditional chunks of 8, then expose only the popcount-many real
    /// entries.
    #[inline]
    fn push_indexes(mut mask: u64, base: u32, out: &mut Vec<u32>) {
        let count = mask.count_ones() as usize;
        if count == 0 {
            return;
        }
        let len = out.len();
        out.reserve(count + 8);
        // SAFETY: capacity covers len + count + 8; chunked writes overshoot
        // by at most 7 entries and set_len exposes only the real ones.
        unsafe {
            let mut ptr = out.as_mut_ptr().add(len);
            let mut remaining = count as isize;
            while remaining > 0 {
                let mut j = 0;
                while j < 8 {
                    *ptr.add(j) = base + mask.trailing_zeros();
                    mask &= mask.wrapping_sub(1);
                    j += 1;
                }
                ptr = ptr.add(8);
                remaining -= 8;
            }
            out.set_len(len + count);
        }
    }
}
