// Generated by vexel from format `logfmt`. Do not edit by hand;
// regenerate with `cargo run --example generate` (in-tree) or the vexel CLI.
//
// Structural indexer: appends to `out` the byte offset of every set bit in
// the format's output bitstream (its structural positions). Self-contained:
// depends only on std.

/// Index the structural positions of `data` into `out`.
pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx2::index_structurals(data, out) };
        return;
    }
    fallback::index_structurals(data, out);
}

/// Portable kernel, public so the dispatch-bypassed path stays testable.
pub mod fallback {
    pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {
        let mut carries = [0u64; 4];
        let mut offset = 0usize;
        while offset + 64 <= data.len() {
            let block: &[u8; 64] = data[offset..offset + 64].try_into().unwrap();
            let mask = step(block, &mut carries);
            push_indexes(mask, offset as u32, out);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            // Mask off bits that fall in the zero padding.
            let mask = step(&block, &mut carries) & ((1u64 << rem) - 1);
            push_indexes(mask, offset as u32, out);
        }
    }

    #[inline]
    fn step(block: &[u8; 64], carries: &mut [u64; 4]) -> u64 {
        let v0 = eq_mask(block, 10u8) | eq_mask(block, 32u8) | eq_mask(block, 61u8); // class "\n ="
        let v1 = eq_mask(block, 34u8); // class "\""
        let v2 = eq_mask(block, 92u8); // class "\\"
        let v3 = { let shifted = (v2 << 1) | carries[0]; carries[0] = v2 >> 63; shifted };
        let v4 = !v3;
        let v5 = v2 & v4;
        let v6 = 0x5555555555555555u64;
        let v7 = 0xaaaaaaaaaaaaaaaau64;
        let v8 = !v2;
        let v9 = v5 & v6;
        let v10 = { let (partial, c1) = v2.overflowing_add(v9); let (sum, c2) = partial.overflowing_add(carries[1]); carries[1] = (c1 | c2) as u64; sum };
        let v11 = v10 & v8;
        let v12 = v11 & v7;
        let v13 = v5 & v7;
        let v14 = { let (partial, c1) = v2.overflowing_add(v13); let (sum, c2) = partial.overflowing_add(carries[2]); carries[2] = (c1 | c2) as u64; sum };
        let v15 = v14 & v8;
        let v16 = v15 & v6;
        let v17 = v12 | v16;
        let v18 = !v17;
        let v19 = v1 & v18;
        let v20 = { let parity = prefix_xor(v19) ^ carries[3]; carries[3] = ((parity as i64) >> 63) as u64; parity };
        let v21 = !v20;
        let v22 = v0 & v21;
        v22
    }

    #[inline]
    fn eq_mask(block: &[u8; 64], byte: u8) -> u64 {
        let mut mask = 0u64;
        let mut i = 0;
        while i < 64 {
            mask |= ((block[i] == byte) as u64) << i;
            i += 1;
        }
        mask
    }

    #[inline]
    fn prefix_xor(mut x: u64) -> u64 {
        x ^= x << 1;
        x ^= x << 2;
        x ^= x << 4;
        x ^= x << 8;
        x ^= x << 16;
        x ^= x << 32;
        x
    }

    #[inline]
    fn push_indexes(mut mask: u64, base: u32, out: &mut Vec<u32>) {
        while mask != 0 {
            out.push(base + mask.trailing_zeros());
            mask &= mask - 1;
        }
    }
}

#[cfg(target_arch = "x86_64")]
mod avx2 {
    use std::arch::x86_64::*;

    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {
        let mut carries = [0u64; 4];
        let mut offset = 0usize;
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let mask = unsafe { step(data.as_ptr().add(offset), &mut carries) };
            push_indexes(mask, offset as u32, out);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let mask = unsafe { step(block.as_ptr(), &mut carries) } & ((1u64 << rem) - 1);
            push_indexes(mask, offset as u32, out);
        }
    }

    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    unsafe fn step(ptr: *const u8, carries: &mut [u64; 4]) -> u64 {
        // SAFETY: caller guarantees 64 readable bytes at `ptr`.
        let (lo, hi) = unsafe {
            (
                _mm256_loadu_si256(ptr as *const __m256i),
                _mm256_loadu_si256(ptr.add(32) as *const __m256i),
            )
        };
        let v0 = eq_mask(lo, hi, 10u8) | eq_mask(lo, hi, 32u8) | eq_mask(lo, hi, 61u8); // class "\n ="
        let v1 = eq_mask(lo, hi, 34u8); // class "\""
        let v2 = eq_mask(lo, hi, 92u8); // class "\\"
        let v3 = { let shifted = (v2 << 1) | carries[0]; carries[0] = v2 >> 63; shifted };
        let v4 = !v3;
        let v5 = v2 & v4;
        let v6 = 0x5555555555555555u64;
        let v7 = 0xaaaaaaaaaaaaaaaau64;
        let v8 = !v2;
        let v9 = v5 & v6;
        let v10 = { let (partial, c1) = v2.overflowing_add(v9); let (sum, c2) = partial.overflowing_add(carries[1]); carries[1] = (c1 | c2) as u64; sum };
        let v11 = v10 & v8;
        let v12 = v11 & v7;
        let v13 = v5 & v7;
        let v14 = { let (partial, c1) = v2.overflowing_add(v13); let (sum, c2) = partial.overflowing_add(carries[2]); carries[2] = (c1 | c2) as u64; sum };
        let v15 = v14 & v8;
        let v16 = v15 & v6;
        let v17 = v12 | v16;
        let v18 = !v17;
        let v19 = v1 & v18;
        let v20 = { let parity = prefix_xor(v19) ^ carries[3]; carries[3] = ((parity as i64) >> 63) as u64; parity };
        let v21 = !v20;
        let v22 = v0 & v21;
        v22
    }

    #[target_feature(enable = "avx2")]
    fn eq_mask(lo: __m256i, hi: __m256i, byte: u8) -> u64 {
        let needle = _mm256_set1_epi8(byte as i8);
        let lo_bits = _mm256_movemask_epi8(_mm256_cmpeq_epi8(lo, needle)) as u32 as u64;
        let hi_bits = _mm256_movemask_epi8(_mm256_cmpeq_epi8(hi, needle)) as u32 as u64;
        lo_bits | (hi_bits << 32)
    }

    #[target_feature(enable = "pclmulqdq")]
    fn prefix_xor(mask: u64) -> u64 {
        let ones = _mm_set1_epi8(-1);
        let value = _mm_set_epi64x(0, mask as i64);
        let product = _mm_clmulepi64_si128::<0>(value, ones);
        _mm_cvtsi128_si64(product) as u64
    }

    /// Branchless bit decoding (simdjson flatten_bits): write indexes in
    /// unconditional chunks of 8, then expose only the popcount-many real
    /// entries.
    #[inline]
    fn push_indexes(mut mask: u64, base: u32, out: &mut Vec<u32>) {
        let count = mask.count_ones() as usize;
        if count == 0 {
            return;
        }
        let len = out.len();
        out.reserve(count + 8);
        // SAFETY: capacity covers len + count + 8; chunked writes overshoot
        // by at most 7 entries and set_len exposes only the real ones.
        unsafe {
            let mut ptr = out.as_mut_ptr().add(len);
            let mut remaining = count as isize;
            while remaining > 0 {
                let mut j = 0;
                while j < 8 {
                    *ptr.add(j) = base + mask.trailing_zeros();
                    mask &= mask.wrapping_sub(1);
                    j += 1;
                }
                ptr = ptr.add(8);
                remaining -= 8;
            }
            out.set_len(len + count);
        }
    }
}
