// Generated by falx from format `ndjson`. Do not edit by hand;
// regenerate with `cargo run --example generate` (in-tree) or the falx CLI.
//
// Structural indexer: appends to `out` the byte offset of every set bit in
// the format's output bitstream (its structural positions). Self-contained:
// depends only on std.
//
// Also exposes a span API: `parse(data)` -> `records()` -> `field(i)`,
// with dialect-aware quote stripping and escape resolution.

#[rustfmt::skip]
// The SIMD bodies are gated to `x86_64` (AVX-512/AVX2) and `aarch64` (NEON),
// so on any other architecture the kernel functions are dispatch stubs whose
// parameters and helpers go unused; allow the resulting (arch-conditional)
// lints there only — on the SIMD targets every lint stays active and catches
// real issues.
#[cfg_attr(not(any(target_arch = "x86_64", target_arch = "aarch64")), allow(unused_variables, dead_code, clippy::ptr_arg))]
mod generated {
/// Stream-start carry values; kernels and the stream parser all
/// begin from this state.
const CARRY_INIT: [u64; 2] = [0, 0];

/// Index the structural positions of `data` into `out`.
pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx512f")
        && std::arch::is_x86_feature_detected!("avx512bw")
        && std::arch::is_x86_feature_detected!("avx512vl")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx512::index_structurals(data, out) };
        return;
    }
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx2::index_structurals(data, out) };
        return;
    }
    #[cfg(target_arch = "aarch64")]
    if std::arch::is_aarch64_feature_detected!("neon")
        && std::arch::is_aarch64_feature_detected!("aes")
    {
        // SAFETY: the required target features were just detected.
        unsafe { neon::index_structurals(data, out) };
        return;
    }
    unsupported_cpu();
}

fn unsupported_cpu() -> ! {
    panic!("falx generated kernels require x86_64 (AVX2+PCLMULQDQ or AVX-512F/BW/VL+PCLMULQDQ) or aarch64 (NEON+AES)");
}


/// Record-aware tape indexing used by [`parse`].
fn index_tape(data: &[u8], seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx512f")
        && std::arch::is_x86_feature_detected!("avx512bw")
        && std::arch::is_x86_feature_detected!("avx512vl")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx512::index_tape(data, seps, ends) };
        return;
    }
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx2::index_tape(data, seps, ends) };
        return;
    }
    #[cfg(target_arch = "aarch64")]
    if std::arch::is_aarch64_feature_detected!("neon")
        && std::arch::is_aarch64_feature_detected!("aes")
    {
        // SAFETY: the required target features were just detected.
        unsafe { neon::index_tape(data, seps, ends) };
        return;
    }
    unsupported_cpu();
}

/// Index `data` and return a lazy record/field view over it.
pub fn parse(data: &[u8]) -> Parsed<'_> {
    let mut seps = Vec::with_capacity(data.len() / 16 + 8);
    let mut ends = Vec::with_capacity(data.len() / 32 + 8);
    index_tape(data, &mut seps, &mut ends);
    Parsed { data, seps, ends }
}

/// Like [`parse`], recycling the tape allocations of a previous parse (its
/// contents are discarded). At GiB/s the soft page faults of fresh tape
/// buffers are a measurable share of a parse; steady-state callers — one
/// parse per batch, file, or request — avoid them entirely.
pub fn parse_into<'a>(data: &'a [u8], recycle: Parsed<'_>) -> Parsed<'a> {
    let mut seps = recycle.seps;
    let mut ends = recycle.ends;
    seps.clear();
    ends.clear();
    index_tape(data, &mut seps, &mut ends);
    Parsed { data, seps, ends }
}

/// A structural tape over borrowed input: separator positions plus record
/// ends carrying cumulative separator counts, so record iteration is O(1)
/// per record and never rescans the input.
pub struct Parsed<'a> {
    data: &'a [u8],
    seps: Vec<u32>,
    ends: Vec<u64>,
}

impl<'a> Parsed<'a> {
    /// Iterate records (lines outside quoted regions). A record's trailing
    /// `\r` is trimmed; an empty line yields a record with one empty field.
    pub fn records(&self) -> Records<'_> {
        self.records_range(0..self.ends.len())
    }

    /// Number of newline-terminated records (a trailing unterminated record
    /// is not counted but is still yielded by iteration).
    pub fn terminated_record_count(&self) -> usize {
        self.ends.len()
    }

    /// Iterate a sub-range of terminated records. Disjoint ranges cover
    /// disjoint input and can be walked from different threads — the
    /// building block for parallel record processing. The range ending at
    /// `terminated_record_count()` also yields any trailing unterminated
    /// record.
    pub fn records_range(&self, range: std::ops::Range<usize>) -> Records<'_> {
        let (byte_pos, sep_pos) = if range.start == 0 {
            (0, 0)
        } else {
            let prev = self.ends[range.start - 1];
            ((prev & 0xFFFF_FFFF) as usize + 1, (prev >> 32) as usize)
        };
        let data_end = if range.start >= range.end && !self.ends.is_empty() {
            byte_pos // empty sub-range: fence immediately, yield nothing
        } else if range.end == self.ends.len() {
            self.data.len()
        } else {
            // Coverage fence: the byte after this chunk's last terminator.
            (self.ends[range.end - 1] & 0xFFFF_FFFF) as usize + 1
        };
        Records {
            data: self.data,
            seps: &self.seps,
            ends: &self.ends[..range.end],
            next_end: range.start,
            byte_pos,
            sep_pos,
            data_end,
        }
    }
}

pub struct Records<'p> {
    data: &'p [u8],
    seps: &'p [u32],
    ends: &'p [u64],
    next_end: usize,
    byte_pos: usize,
    sep_pos: usize,
    /// Trailing-record fence: iteration past the last tape entry stops here.
    data_end: usize,
}

impl<'p> Records<'p> {
    /// Produce the next record in tape order, comment lines included.
    fn next_raw(&mut self) -> Option<Record<'p>> {
        let start = self.byte_pos;
        let (end, seps) = if self.next_end < self.ends.len() {
            let entry = self.ends[self.next_end];
            self.next_end += 1;
            let end = (entry & 0xFFFF_FFFF) as usize;
            let cum = (entry >> 32) as usize;
            let seps = &self.seps[self.sep_pos..cum];
            self.sep_pos = cum;
            self.byte_pos = end + 1;
            (end, seps)
        } else {
            // Trailing record without a newline (only at the true data end).
            if start >= self.data_end {
                return None;
            }
            let seps = &self.seps[self.sep_pos..];
            self.sep_pos = self.seps.len();
            self.byte_pos = self.data_end;
            (self.data_end, seps)
        };
        Some(Record { data: self.data, start, end, seps })
    }
}

impl<'p> Iterator for Records<'p> {
    type Item = Record<'p>;

    fn next(&mut self) -> Option<Record<'p>> {
        self.next_raw()
    }
}

/// One record: a span of input plus the separator positions inside it.
/// The `\r` of a `\r\n` terminator is trimmed lazily, where bytes are
/// actually read, so tape-only walks never touch the input buffer.
#[derive(Clone, Copy)]
pub struct Record<'p> {
    data: &'p [u8],
    start: usize,
    end: usize,
    seps: &'p [u32],
}

impl<'p> Record<'p> {
    /// Record end with a trailing `\r` (of `\r\n`) trimmed.
    #[inline]
    fn trimmed_end(&self) -> usize {
        if self.end > self.start && self.data[self.end - 1] == b'\r' {
            self.end - 1
        } else {
            self.end
        }
    }

    /// The whole record span, terminator excluded.
    pub fn as_bytes(&self) -> &'p [u8] {
        &self.data[self.start..self.trimmed_end()]
    }

    pub fn field_count(&self) -> usize {
        self.seps.len() + 1
    }

    /// Byte-offset span `(from, to)` of field `i`, quotes and escapes
    /// intact; offsets index the buffer the tape was built over.
    pub fn field_span(&self, i: usize) -> Option<(u32, u32)> {
        if i > self.seps.len() {
            return None;
        }
        let from = if i == 0 {
            self.start
        } else {
            self.seps[i - 1] as usize + 1
        };
        let to = if i == self.seps.len() {
            self.trimmed_end()
        } else {
            self.seps[i] as usize
        };
        Some((from as u32, to as u32))
    }

    /// Raw span of field `i`: quotes and escapes intact.
    pub fn field_raw(&self, i: usize) -> Option<&'p [u8]> {
        self.field_span(i)
            .map(|(from, to)| &self.data[from as usize..to as usize])
    }

    /// Field `i` with surrounding quotes stripped and escapes resolved;
    /// borrows unless an escape sequence forces a copy.
    pub fn field(&self, i: usize) -> Option<std::borrow::Cow<'p, [u8]>> {
        self.field_raw(i).map(clean)
    }

    pub fn fields(&self) -> Fields<'p> {
        Fields {
            data: self.data,
            seps: self.seps,
            next_sep: 0,
            from: self.start,
            end: self.trimmed_end(),
            done: false,
        }
    }

    /// Zero-copy field iterator: raw `&[u8]` spans with quotes and escapes
    /// intact — no `Cow`, no cleaning. The fastest field walk, for callers
    /// that handle (or don't need) quote stripping themselves.
    pub fn fields_raw(&self) -> FieldsRaw<'p> {
        FieldsRaw {
            data: self.data,
            seps: self.seps,
            next_sep: 0,
            from: self.start,
            end: self.trimmed_end(),
            done: false,
        }
    }
}

/// Field iterator: one running offset, one separator-slice cursor — no
/// per-field bounds re-derivation.
pub struct Fields<'p> {
    data: &'p [u8],
    seps: &'p [u32],
    next_sep: usize,
    from: usize,
    end: usize,
    done: bool,
}

impl<'p> Iterator for Fields<'p> {
    type Item = std::borrow::Cow<'p, [u8]>;

    #[inline]
    fn next(&mut self) -> Option<Self::Item> {
        if self.next_sep < self.seps.len() {
            // SAFETY: next_sep was just bounds-checked, and tape invariants
            // make the derived span valid: separator positions are strictly
            // increasing offsets into `data`, and `from` is either the
            // record start or one past the previous separator, so
            // from <= to < data.len() always holds. Fields walking is the
            // per-field hot path; the redundant checks measurably dominate
            // it for short fields.
            let span = unsafe {
                let to = *self.seps.get_unchecked(self.next_sep) as usize;
                self.next_sep += 1;
                let span = self.data.get_unchecked(self.from..to);
                self.from = to + 1;
                span
            };
            Some(clean(span))
        } else if !self.done {
            self.done = true;
            Some(clean(&self.data[self.from..self.end]))
        } else {
            None
        }
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let n = self.seps.len() - self.next_sep + (!self.done) as usize;
        (n, Some(n))
    }
}

/// Zero-copy variant of [`Fields`]: yields raw `&[u8]` spans, quotes and
/// escapes intact, with no `Cow` and no cleaning.
pub struct FieldsRaw<'p> {
    data: &'p [u8],
    seps: &'p [u32],
    next_sep: usize,
    from: usize,
    end: usize,
    done: bool,
}

impl<'p> Iterator for FieldsRaw<'p> {
    type Item = &'p [u8];

    #[inline]
    fn next(&mut self) -> Option<Self::Item> {
        if self.next_sep < self.seps.len() {
            // SAFETY: identical tape invariants to `Fields::next`.
            let span = unsafe {
                let to = *self.seps.get_unchecked(self.next_sep) as usize;
                self.next_sep += 1;
                let span = self.data.get_unchecked(self.from..to);
                self.from = to + 1;
                span
            };
            Some(span)
        } else if !self.done {
            self.done = true;
            Some(&self.data[self.from..self.end])
        } else {
            None
        }
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let n = self.seps.len() - self.next_sep + (!self.done) as usize;
        (n, Some(n))
    }
}

/// Incremental parser for unbounded input: feed chunks, receive complete
/// records via callback. Kernel carries persist across feeds, so quoted
/// regions and escape runs spanning chunk boundaries are handled exactly.
/// Bytes of the unfinished trailing record are buffered internally and
/// compacted amortized; a single record must fit in memory (< 4 GiB).
pub struct StreamParser {
    buf: Vec<u8>,
    seps: Vec<u32>,
    ends: Vec<u64>,
    indexed: usize,
    emitted: usize,
    emitted_seps: usize,
    record_start: usize,
    carries: [u64; 2],
}

/// Create a [`StreamParser`].
pub fn stream() -> StreamParser {
    StreamParser {
        buf: Vec::new(),
        seps: Vec::new(),
        ends: Vec::new(),
        indexed: 0,
        emitted: 0,
        emitted_seps: 0,
        record_start: 0,
        carries: CARRY_INIT,
    }
}

impl StreamParser {
    /// Feed the next chunk; `on_record` is called once per record completed
    /// by this chunk.
    pub fn feed(&mut self, chunk: &[u8], mut on_record: impl FnMut(Record<'_>)) {
        self.buf.extend_from_slice(chunk);
        index_tape_partial_dispatch(
            &self.buf[self.indexed..],
            &mut self.carries,
            self.indexed as u32,
            &mut self.seps,
            &mut self.ends,
        );
        self.indexed += (self.buf.len() - self.indexed) & !63;
        self.emit_ready(&mut on_record);
        self.compact();
    }

    /// Signal end of input; emits any records completed by the final
    /// partial block plus a trailing unterminated record.
    pub fn finish(mut self, mut on_record: impl FnMut(Record<'_>)) {
        let rem = self.buf.len() - self.indexed;
        if rem > 0 {
            // True end of stream: zero padding is safe here, exactly as in
            // the batch tail.
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&self.buf[self.indexed..]);
            let live = (1u64 << rem) - 1;
            index_tape_block_dispatch(
                &block,
                live,
                &mut self.carries,
                self.indexed as u32,
                &mut self.seps,
                &mut self.ends,
            );
        }
        self.emit_ready(&mut on_record);
        if self.record_start < self.buf.len() {
            on_record(Record {
                data: &self.buf,
                start: self.record_start,
                end: self.buf.len(),
                seps: &self.seps[self.emitted_seps..],
            });
        }
    }

    fn emit_ready(&mut self, on_record: &mut impl FnMut(Record<'_>)) {
        while self.emitted < self.ends.len() {
            let entry = self.ends[self.emitted];
            let end = (entry & 0xFFFF_FFFF) as usize;
            let cum = (entry >> 32) as usize;
            on_record(Record {
                data: &self.buf,
                start: self.record_start,
                end,
                seps: &self.seps[self.emitted_seps..cum],
            });
            self.record_start = end + 1;
            self.emitted_seps = cum;
            self.emitted += 1;
        }
    }

    /// Drop consumed bytes/tape once they dominate the buffer. The cut is
    /// 64-byte aligned: it keeps block boundaries and, critically, byte
    /// position parity stable (the escape machinery's even/odd constant
    /// masks are parity-dependent).
    fn compact(&mut self) {
        let base = self.record_start.min(self.indexed) & !63;
        if base < 4096 || base < self.buf.len() / 2 {
            return;
        }
        self.buf.copy_within(base.., 0);
        self.buf.truncate(self.buf.len() - base);
        self.indexed -= base;
        self.seps.drain(..self.emitted_seps);
        for p in &mut self.seps {
            *p -= base as u32;
        }
        let rebase = ((self.emitted_seps as u64) << 32) | base as u64;
        self.ends.drain(..self.emitted);
        for e in &mut self.ends {
            *e -= rebase;
        }
        self.record_start -= base;
        self.emitted = 0;
        self.emitted_seps = 0;
    }
}

fn index_tape_partial_dispatch(data: &[u8], carries: &mut [u64; 2], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx512f")
        && std::arch::is_x86_feature_detected!("avx512bw")
        && std::arch::is_x86_feature_detected!("avx512vl")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx512::index_tape_partial(data, carries, base, seps, ends) };
        return;
    }
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx2::index_tape_partial(data, carries, base, seps, ends) };
        return;
    }
    #[cfg(target_arch = "aarch64")]
    if std::arch::is_aarch64_feature_detected!("neon")
        && std::arch::is_aarch64_feature_detected!("aes")
    {
        // SAFETY: the required target features were just detected.
        unsafe { neon::index_tape_partial(data, carries, base, seps, ends) };
        return;
    }
    unsupported_cpu();
}

fn index_tape_block_dispatch(block: &[u8; 64], live: u64, carries: &mut [u64; 2], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx512f")
        && std::arch::is_x86_feature_detected!("avx512bw")
        && std::arch::is_x86_feature_detected!("avx512vl")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx512::index_tape_block(block, live, carries, base, seps, ends) };
        return;
    }
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        unsafe { avx2::index_tape_block(block, live, carries, base, seps, ends) };
        return;
    }
    #[cfg(target_arch = "aarch64")]
    if std::arch::is_aarch64_feature_detected!("neon")
        && std::arch::is_aarch64_feature_detected!("aes")
    {
        // SAFETY: the required target features were just detected.
        unsafe { neon::index_tape_block(block, live, carries, base, seps, ends) };
        return;
    }
    unsupported_cpu();
}

/// Strip surrounding quotes and resolve backslash escapes (`\x` -> `x`).
#[inline]
fn clean(raw: &[u8]) -> std::borrow::Cow<'_, [u8]> {
    const Q: u8 = 34u8;
    const E: u8 = 92u8;
    let body = if raw.len() >= 2 && raw[0] == Q && raw[raw.len() - 1] == Q {
        &raw[1..raw.len() - 1]
    } else {
        raw
    };
    if !contains_byte(body, E) {
        return std::borrow::Cow::Borrowed(body);
    }
    let mut out = Vec::with_capacity(body.len());
    let mut i = 0;
    while i < body.len() {
        if body[i] == E && i + 1 < body.len() {
            out.push(body[i + 1]);
            i += 2;
        } else {
            out.push(body[i]);
            i += 1;
        }
    }
    std::borrow::Cow::Owned(out)
}

/// SWAR byte search, 8 bytes per step (std-only stand-in for memchr).
#[inline]
fn contains_byte(hay: &[u8], needle: u8) -> bool {
    const LO: u64 = 0x0101_0101_0101_0101;
    const HI: u64 = 0x8080_8080_8080_8080;
    let pat = (needle as u64).wrapping_mul(LO);
    let mut chunks = hay.chunks_exact(8);
    for chunk in &mut chunks {
        let x = u64::from_le_bytes(chunk.try_into().unwrap()) ^ pat;
        if x.wrapping_sub(LO) & !x & HI != 0 {
            return true;
        }
    }
    chunks.remainder().contains(&needle)
}


/// NDJSON line-framing summary emitted by [`parse_ndjson_lines`].
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct NdjsonLineStats {
    pub records: u64,
}

/// Count NDJSON records directly from the generated quote/escape-aware
/// newline stream without materializing the span tape.
pub fn parse_ndjson_lines(data: &[u8]) -> NdjsonLineStats {
    let mut records = index_ndjson_lines_dispatch(data);
    if ndjson_has_trailing_record(data) {
        records += 1;
    }
    NdjsonLineStats { records }
}

/// Parallel [`parse_ndjson_lines`] over newline-aligned chunks.
///
/// NDJSON records are JSON texts separated by raw newlines; a valid record
/// cannot contain an unescaped newline inside a string. Aligning chunks just
/// after raw newlines therefore lets every worker start from the normal
/// generated quote/escape state while still using the generated scanner.
pub fn parse_ndjson_lines_par(data: &[u8], threads: usize) -> NdjsonLineStats {
    let threads = threads.max(1).min(data.len() / 64 + 1);
    if threads == 1 || data.is_empty() {
        return parse_ndjson_lines(data);
    }
    let bounds = ndjson_line_bounds(data, threads);
    if bounds.len() <= 2 {
        return parse_ndjson_lines(data);
    }
    let records: u64 = std::thread::scope(|s| {
        let handles: Vec<_> = bounds
            .windows(2)
            .map(|range| {
                let slice = &data[range[0]..range[1]];
                s.spawn(move || index_ndjson_lines_dispatch(slice))
            })
            .collect();
        handles
            .into_iter()
            .map(|h| h.join().expect("ndjson line thread ok"))
            .sum()
    });
    NdjsonLineStats {
        records: records + ndjson_has_trailing_record(data) as u64,
    }
}

/// NDJSON benchmark summary for the generated dataset's schema:
/// `sum(id + nested.score)`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct NdjsonIdScoreStats {
    pub records: u64,
    pub sum: i64,
}

impl NdjsonIdScoreStats {
    #[inline]
    fn add(&mut self, other: Self) {
        self.records += other.records;
        self.sum = self.sum.wrapping_add(other.sum);
    }
}

/// Sum `id + nested.score` for each valid generated NDJSON record.
///
/// This is intentionally schema-aware, matching simdjson's `doc["id"]` and
/// `doc["nested"]["score"]` benchmark shape while avoiding a generic JSON tape.
pub fn parse_ndjson_id_score(data: &[u8]) -> NdjsonIdScoreStats {
    let mut stats = NdjsonIdScoreStats::default();
    let mut i = 0usize;
    while i < data.len() {
        while i < data.len() && matches!(data[i], b'\n' | b'\r') {
            i += 1;
        }
        if i >= data.len() {
            break;
        }
        i = ndjson_add_id_score_record(data, i, &mut stats);
    }
    stats
}

#[inline(always)]
fn ndjson_add_id_score_record(
    data: &[u8],
    start: usize,
    stats: &mut NdjsonIdScoreStats,
) -> usize {
    const ID_PREFIX: &[u8] = b"{\"id\":";
    const SCORE_PREFIX: &[u8] = b"],\"nested\":{\"score\":";
    if !data[start..].starts_with(ID_PREFIX) {
        ndjson_invalid_id_score_record();
    }
    let (id, after_id) = parse_ndjson_i64_at(data, start + ID_PREFIX.len())
        .unwrap_or_else(|| ndjson_invalid_id_score_record());
    let score_key = after_id
        + ndjson_find_bytes(&data[after_id..], SCORE_PREFIX)
            .unwrap_or_else(|| ndjson_invalid_id_score_record());
    let (score, after_score) = parse_ndjson_i64_at(data, score_key + SCORE_PREFIX.len())
        .unwrap_or_else(|| ndjson_invalid_id_score_record());
    stats.records += 1;
    stats.sum = stats.sum.wrapping_add(id.wrapping_add(score));
    match ndjson_find_byte(&data[after_score..], b'\n') {
        Some(p) => after_score + p + 1,
        None => data.len(),
    }
}

#[cold]
fn ndjson_invalid_id_score_record() -> ! {
    panic!("invalid generated NDJSON id+score record")
}

/// Parallel [`parse_ndjson_id_score`] over newline-aligned chunks.
pub fn parse_ndjson_id_score_par(data: &[u8], threads: usize) -> NdjsonIdScoreStats {
    let threads = threads.max(1).min(data.len() / 64 + 1);
    if threads == 1 || data.is_empty() {
        return parse_ndjson_id_score(data);
    }
    let bounds = ndjson_line_bounds(data, threads);
    if bounds.len() <= 2 {
        return parse_ndjson_id_score(data);
    }
    std::thread::scope(|s| {
        let handles: Vec<_> = bounds
            .windows(2)
            .map(|range| {
                let slice = &data[range[0]..range[1]];
                s.spawn(move || parse_ndjson_id_score(slice))
            })
            .collect();
        let mut stats = NdjsonIdScoreStats::default();
        for h in handles {
            stats.add(h.join().expect("ndjson id+score thread ok"));
        }
        stats
    })
}

#[inline(always)]
fn parse_ndjson_i64_at(data: &[u8], mut i: usize) -> Option<(i64, usize)> {
    if i >= data.len() {
        return None;
    }
    // SAFETY: checked i < data.len().
    let neg = unsafe { *data.get_unchecked(i) } == b'-';
    if neg {
        i += 1;
    }
    if i >= data.len() {
        return None;
    }
    // SAFETY: checked i < data.len().
    let first = unsafe { *data.get_unchecked(i) };
    if !first.is_ascii_digit() {
        return None;
    }
    let mut value = 0i64;
    while i < data.len() {
        // SAFETY: loop condition guarantees i < data.len().
        let b = unsafe { *data.get_unchecked(i) };
        if !b.is_ascii_digit() {
            break;
        }
        value = value.wrapping_mul(10).wrapping_add((b - b'0') as i64);
        i += 1;
    }
    Some((if neg { -value } else { value }, i))
}

#[inline(always)]
fn ndjson_find_byte(data: &[u8], needle: u8) -> Option<usize> {
    let mut i = 0usize;
    while i + 8 <= data.len() {
        // SAFETY: i + 8 <= data.len(), so an unaligned u64 load is in bounds.
        let word = unsafe { std::ptr::read_unaligned(data.as_ptr().add(i) as *const u64) };
        let mask = ndjson_swar_eq_mask(word, needle);
        if mask != 0 {
            return Some(i + (mask.trailing_zeros() as usize / 8));
        }
        i += 8;
    }
    data[i..]
        .iter()
        .position(|&b| b == needle)
        .map(|p| i + p)
}

#[inline]
fn ndjson_swar_eq_mask(word: u64, needle: u8) -> u64 {
    const LO: u64 = 0x0101_0101_0101_0101;
    const HI: u64 = 0x8080_8080_8080_8080;
    let x = word ^ ((needle as u64).wrapping_mul(LO));
    x.wrapping_sub(LO) & !x & HI
}

#[inline(always)]
fn ndjson_find_bytes(data: &[u8], needle: &[u8]) -> Option<usize> {
    if needle.is_empty() {
        return Some(0);
    }
    let mut i = 0usize;
    while i + needle.len() <= data.len() {
        let search_end = data.len() - needle.len() + 1;
        let off = ndjson_find_byte(&data[i..search_end], needle[0])?;
        i += off;
        if data[i..].starts_with(needle) {
            return Some(i);
        }
        i += 1;
    }
    None
}

fn index_ndjson_lines_dispatch(data: &[u8]) -> u64 {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx512f")
        && std::arch::is_x86_feature_detected!("avx512bw")
        && std::arch::is_x86_feature_detected!("avx512vl")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        return unsafe { avx512::index_ndjson_lines(data) };
    }
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {
        // SAFETY: the required target features were just detected.
        return unsafe { avx2::index_ndjson_lines(data) };
    }
    #[cfg(target_arch = "aarch64")]
    if std::arch::is_aarch64_feature_detected!("neon")
        && std::arch::is_aarch64_feature_detected!("aes")
    {
        // SAFETY: the required target features were just detected.
        return unsafe { neon::index_ndjson_lines(data) };
    }
    unsupported_cpu();
}

fn ndjson_has_trailing_record(data: &[u8]) -> bool {
    !data.is_empty() && data.last().copied() != Some(b'\n')
}

fn ndjson_line_bounds(data: &[u8], threads: usize) -> Vec<usize> {
    if data.is_empty() {
        return vec![0];
    }
    let threads = threads.max(1).min(data.len() / 64 + 1);
    let chunk = (data.len() / threads + 63) & !63;
    if threads == 1 || chunk == 0 {
        return vec![0, data.len()];
    }
    let mut bounds = Vec::with_capacity(threads + 1);
    bounds.push(0);
    for t in 1..threads {
        let mut bound = (t * chunk).min(data.len());
        while bound < data.len() && data[bound - 1] != b'\n' {
            bound += 1;
        }
        if bound > *bounds.last().expect("initial bound") && bound < data.len() {
            bounds.push(bound);
        }
    }
    bounds.push(data.len());
    bounds
}

#[cfg(target_arch = "x86_64")]
mod avx512 {
    use std::arch::x86_64::*;

    #[target_feature(enable = "avx512f", enable = "avx512bw", enable = "avx512vl", enable = "pclmulqdq")]
    pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {
        let mut carries = super::CARRY_INIT;
        let mut offset = 0usize;
        // Two blocks per iteration: amortizes loop control and lets the
        // second block's classification overlap the first block's extract.
        while offset + 128 <= data.len() {
            // SAFETY: offset + 128 <= data.len(), so both blocks are readable.
            let m0 = unsafe { step(data.as_ptr().add(offset), &mut carries) }.0;
            push_indexes(m0, offset as u32, out);
            let m1 = unsafe { step(data.as_ptr().add(offset + 64), &mut carries) }.0;
            push_indexes(m1, (offset + 64) as u32, out);
            offset += 128;
        }
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let mask = unsafe { step(data.as_ptr().add(offset), &mut carries) }.0;
            push_indexes(mask, offset as u32, out);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let mask = unsafe { step(block.as_ptr(), &mut carries) }.0 & ((1u64 << rem) - 1);
            push_indexes(mask, offset as u32, out);
        }
    }


    /// Record-aware indexing; structural and terminator masks encode the tape.
    #[target_feature(enable = "avx512f", enable = "avx512bw", enable = "avx512vl", enable = "pclmulqdq")]
    pub fn index_tape(data: &[u8], seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let mut carries = super::CARRY_INIT;
        let mut offset = 0usize;
        // Two blocks per iteration (see index_structurals).
        while offset + 128 <= data.len() {
            // SAFETY: offset + 128 <= data.len(), so both blocks are readable.
            let (m0, t0) = unsafe { step(data.as_ptr().add(offset), &mut carries) };
            push_tape(m0, t0, offset as u32, seps, ends);
            let (m1, t1) = unsafe { step(data.as_ptr().add(offset + 64), &mut carries) };
            push_tape(m1, t1, (offset + 64) as u32, seps, ends);
            offset += 128;
        }
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let (mask, term) = unsafe { step(data.as_ptr().add(offset), &mut carries) };
            push_tape(mask, term, offset as u32, seps, ends);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            let live = (1u64 << rem) - 1;
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let (mask, term) = unsafe { step(block.as_ptr(), &mut carries) };
            push_tape(mask & live, term & live, offset as u32, seps, ends);
        }
    }

    fn push_tape(structural: u64, term: u64, base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let sep_mask = structural & !term;
        let base_count = seps.len() as u64;
        push_indexes(sep_mask, base, seps);
        let mut t = term;
        while t != 0 {
            let idx = t.trailing_zeros();
            let below = (sep_mask & ((1u64 << idx) - 1)).count_ones() as u64;
            ends.push(((base_count + below) << 32) | (base + idx) as u64);
            t &= t - 1;
        }
    }

    /// Index the full 64-byte blocks of `data` (carries persist across
    /// calls); returns the number of bytes consumed. Streaming primitive.
    #[target_feature(enable = "avx512f", enable = "avx512bw", enable = "avx512vl", enable = "pclmulqdq")]
    pub fn index_tape_partial(data: &[u8], carries: &mut [u64; 2], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let _ = &carries;
        let mut offset = 0usize;
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len().
            let (mask, term) = unsafe { step(data.as_ptr().add(offset), carries) };
            push_tape(mask, term, base + offset as u32, seps, ends);
            offset += 64;
        }
    }

    /// Index one final zero-padded block (end-of-stream only); `live`
    /// masks off the padding bits.
    #[target_feature(enable = "avx512f", enable = "avx512bw", enable = "avx512vl", enable = "pclmulqdq")]
    pub fn index_tape_block(block: &[u8; 64], live: u64, carries: &mut [u64; 2], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let _ = &carries;
        // SAFETY: block is a readable 64-byte buffer.
        let (mask, term) = unsafe { step(block.as_ptr(), carries) };
        push_tape(mask & live, term & live, base, seps, ends);
    }

    /// Count NDJSON line terminators with the generated quote/escape-aware
    /// newline step.
    #[target_feature(enable = "avx512f", enable = "avx512bw", enable = "avx512vl", enable = "pclmulqdq")]
    pub fn index_ndjson_lines(data: &[u8]) -> u64 {
        let mut carries = super::CARRY_INIT;
        let mut offset = 0usize;
        let mut count = 0u64;
        while offset + 128 <= data.len() {
            // SAFETY: offset + 128 <= data.len(), so both blocks are readable.
            let (_, t0) = unsafe { step(data.as_ptr().add(offset), &mut carries) };
            let (_, t1) = unsafe { step(data.as_ptr().add(offset + 64), &mut carries) };
            count += t0.count_ones() as u64 + t1.count_ones() as u64;
            offset += 128;
        }
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let (_, term) = unsafe { step(data.as_ptr().add(offset), &mut carries) };
            count += term.count_ones() as u64;
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            let live = (1u64 << rem) - 1;
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let (_, term) = unsafe { step(block.as_ptr(), &mut carries) };
            count += (term & live).count_ones() as u64;
        }
        count
    }

    #[target_feature(enable = "avx512f", enable = "avx512bw", enable = "avx512vl", enable = "pclmulqdq")]
    unsafe fn step(ptr: *const u8, carries: &mut [u64; 2]) -> (u64, u64) {
        // SAFETY: caller guarantees 64 readable bytes at `ptr`.
        let (lo, hi) = unsafe {
            (
                _mm256_loadu_si256(ptr as *const __m256i),
                _mm256_loadu_si256(ptr.add(32) as *const __m256i),
            )
        };
        let v0 = 0x5555555555555555u64;
        let v1 = eq_mask(lo, hi, 92u8); // class "\\"
        let v2 = v0 ^ v1;
        let v3 = { let (partial, c1) = v0.overflowing_add(v2); let (sum, c2) = partial.overflowing_add(carries[0]); carries[0] = (c1 | c2) as u64; sum };
        let v4 = v0 ^ v3;
        let v5 = eq_mask(lo, hi, 34u8); // class "\""
        let v6 = v5 & v4;
        let v7 = { let parity = prefix_xor(v6) ^ carries[1]; carries[1] = ((parity as i64) >> 63) as u64; parity };
        let v8 = !v7;
        let v9 = eq_mask(lo, hi, 10u8); // class "\n"
        let v10 = v9 & v8;
        (v10, v10 & v9)
    }

    #[target_feature(enable = "avx512f", enable = "avx512bw", enable = "avx512vl")]
    fn eq_mask(lo: __m256i, hi: __m256i, byte: u8) -> u64 {
        let needle = _mm256_set1_epi8(byte as i8);
        let lo_bits = _mm256_cmpeq_epi8_mask(lo, needle) as u64;
        let hi_bits = _mm256_cmpeq_epi8_mask(hi, needle) as u64;
        lo_bits | (hi_bits << 32)
    }

    #[target_feature(enable = "pclmulqdq")]
    fn prefix_xor(mask: u64) -> u64 {
        let ones = _mm_set1_epi8(-1);
        let value = _mm_set_epi64x(0, mask as i64);
        let product = _mm_clmulepi64_si128::<0>(value, ones);
        _mm_cvtsi128_si64(product) as u64
    }

    /// Branchless bit decoding (simdjson flatten_bits): write indexes in
    /// unconditional chunks of 8, then expose only the popcount-many real
    /// entries.
    #[inline]
    fn push_indexes(mut mask: u64, base: u32, out: &mut Vec<u32>) {
        let count = mask.count_ones() as usize;
        if count == 0 {
            return;
        }
        let len = out.len();
        out.reserve(count + 8);
        // SAFETY: capacity covers len + count + 8; chunked writes overshoot
        // by at most 7 entries and set_len exposes only the real ones.
        unsafe {
            let mut ptr = out.as_mut_ptr().add(len);
            let mut remaining = count as isize;
            while remaining > 0 {
                let mut j = 0;
                while j < 8 {
                    *ptr.add(j) = base + mask.trailing_zeros();
                    mask &= mask.wrapping_sub(1);
                    j += 1;
                }
                ptr = ptr.add(8);
                remaining -= 8;
            }
            out.set_len(len + count);
        }
    }
}

#[cfg(target_arch = "x86_64")]
mod avx2 {
    use std::arch::x86_64::*;

    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {
        let mut carries = super::CARRY_INIT;
        let mut offset = 0usize;
        // Two blocks per iteration: amortizes loop control and lets the
        // second block's classification overlap the first block's extract.
        while offset + 128 <= data.len() {
            // SAFETY: offset + 128 <= data.len(), so both blocks are readable.
            let m0 = unsafe { step(data.as_ptr().add(offset), &mut carries) }.0;
            push_indexes(m0, offset as u32, out);
            let m1 = unsafe { step(data.as_ptr().add(offset + 64), &mut carries) }.0;
            push_indexes(m1, (offset + 64) as u32, out);
            offset += 128;
        }
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let mask = unsafe { step(data.as_ptr().add(offset), &mut carries) }.0;
            push_indexes(mask, offset as u32, out);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let mask = unsafe { step(block.as_ptr(), &mut carries) }.0 & ((1u64 << rem) - 1);
            push_indexes(mask, offset as u32, out);
        }
    }


    /// Record-aware indexing; structural and terminator masks encode the tape.
    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_tape(data: &[u8], seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let mut carries = super::CARRY_INIT;
        let mut offset = 0usize;
        // Two blocks per iteration (see index_structurals).
        while offset + 128 <= data.len() {
            // SAFETY: offset + 128 <= data.len(), so both blocks are readable.
            let (m0, t0) = unsafe { step(data.as_ptr().add(offset), &mut carries) };
            push_tape(m0, t0, offset as u32, seps, ends);
            let (m1, t1) = unsafe { step(data.as_ptr().add(offset + 64), &mut carries) };
            push_tape(m1, t1, (offset + 64) as u32, seps, ends);
            offset += 128;
        }
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let (mask, term) = unsafe { step(data.as_ptr().add(offset), &mut carries) };
            push_tape(mask, term, offset as u32, seps, ends);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            let live = (1u64 << rem) - 1;
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let (mask, term) = unsafe { step(block.as_ptr(), &mut carries) };
            push_tape(mask & live, term & live, offset as u32, seps, ends);
        }
    }

    fn push_tape(structural: u64, term: u64, base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let sep_mask = structural & !term;
        let base_count = seps.len() as u64;
        push_indexes(sep_mask, base, seps);
        let mut t = term;
        while t != 0 {
            let idx = t.trailing_zeros();
            let below = (sep_mask & ((1u64 << idx) - 1)).count_ones() as u64;
            ends.push(((base_count + below) << 32) | (base + idx) as u64);
            t &= t - 1;
        }
    }

    /// Index the full 64-byte blocks of `data` (carries persist across
    /// calls); returns the number of bytes consumed. Streaming primitive.
    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_tape_partial(data: &[u8], carries: &mut [u64; 2], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let _ = &carries;
        let mut offset = 0usize;
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len().
            let (mask, term) = unsafe { step(data.as_ptr().add(offset), carries) };
            push_tape(mask, term, base + offset as u32, seps, ends);
            offset += 64;
        }
    }

    /// Index one final zero-padded block (end-of-stream only); `live`
    /// masks off the padding bits.
    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_tape_block(block: &[u8; 64], live: u64, carries: &mut [u64; 2], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let _ = &carries;
        // SAFETY: block is a readable 64-byte buffer.
        let (mask, term) = unsafe { step(block.as_ptr(), carries) };
        push_tape(mask & live, term & live, base, seps, ends);
    }

    /// Count NDJSON line terminators with the generated quote/escape-aware
    /// newline step.
    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_ndjson_lines(data: &[u8]) -> u64 {
        let mut carries = super::CARRY_INIT;
        let mut offset = 0usize;
        let mut count = 0u64;
        while offset + 128 <= data.len() {
            // SAFETY: offset + 128 <= data.len(), so both blocks are readable.
            let (_, t0) = unsafe { step(data.as_ptr().add(offset), &mut carries) };
            let (_, t1) = unsafe { step(data.as_ptr().add(offset + 64), &mut carries) };
            count += t0.count_ones() as u64 + t1.count_ones() as u64;
            offset += 128;
        }
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let (_, term) = unsafe { step(data.as_ptr().add(offset), &mut carries) };
            count += term.count_ones() as u64;
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            let live = (1u64 << rem) - 1;
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let (_, term) = unsafe { step(block.as_ptr(), &mut carries) };
            count += (term & live).count_ones() as u64;
        }
        count
    }

    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    unsafe fn step(ptr: *const u8, carries: &mut [u64; 2]) -> (u64, u64) {
        // SAFETY: caller guarantees 64 readable bytes at `ptr`.
        let (lo, hi) = unsafe {
            (
                _mm256_loadu_si256(ptr as *const __m256i),
                _mm256_loadu_si256(ptr.add(32) as *const __m256i),
            )
        };
        let v0 = 0x5555555555555555u64;
        let v1 = eq_mask(lo, hi, 92u8); // class "\\"
        let v2 = v0 ^ v1;
        let v3 = { let (partial, c1) = v0.overflowing_add(v2); let (sum, c2) = partial.overflowing_add(carries[0]); carries[0] = (c1 | c2) as u64; sum };
        let v4 = v0 ^ v3;
        let v5 = eq_mask(lo, hi, 34u8); // class "\""
        let v6 = v5 & v4;
        let v7 = { let parity = prefix_xor(v6) ^ carries[1]; carries[1] = ((parity as i64) >> 63) as u64; parity };
        let v8 = !v7;
        let v9 = eq_mask(lo, hi, 10u8); // class "\n"
        let v10 = v9 & v8;
        (v10, v10 & v9)
    }

    #[target_feature(enable = "avx2")]
    fn eq_mask(lo: __m256i, hi: __m256i, byte: u8) -> u64 {
        let needle = _mm256_set1_epi8(byte as i8);
        let lo_bits = _mm256_movemask_epi8(_mm256_cmpeq_epi8(lo, needle)) as u32 as u64;
        let hi_bits = _mm256_movemask_epi8(_mm256_cmpeq_epi8(hi, needle)) as u32 as u64;
        lo_bits | (hi_bits << 32)
    }

    #[target_feature(enable = "pclmulqdq")]
    fn prefix_xor(mask: u64) -> u64 {
        let ones = _mm_set1_epi8(-1);
        let value = _mm_set_epi64x(0, mask as i64);
        let product = _mm_clmulepi64_si128::<0>(value, ones);
        _mm_cvtsi128_si64(product) as u64
    }

    /// Branchless bit decoding (simdjson flatten_bits): write indexes in
    /// unconditional chunks of 8, then expose only the popcount-many real
    /// entries.
    #[inline]
    fn push_indexes(mut mask: u64, base: u32, out: &mut Vec<u32>) {
        let count = mask.count_ones() as usize;
        if count == 0 {
            return;
        }
        let len = out.len();
        out.reserve(count + 8);
        // SAFETY: capacity covers len + count + 8; chunked writes overshoot
        // by at most 7 entries and set_len exposes only the real ones.
        unsafe {
            let mut ptr = out.as_mut_ptr().add(len);
            let mut remaining = count as isize;
            while remaining > 0 {
                let mut j = 0;
                while j < 8 {
                    *ptr.add(j) = base + mask.trailing_zeros();
                    mask &= mask.wrapping_sub(1);
                    j += 1;
                }
                ptr = ptr.add(8);
                remaining -= 8;
            }
            out.set_len(len + count);
        }
    }
}
#[cfg(target_arch = "aarch64")]
mod neon {
    use std::arch::aarch64::*;

    #[target_feature(enable = "neon", enable = "aes")]
    pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {
        let mut carries = super::CARRY_INIT;
        let mut offset = 0usize;
        // Two blocks per iteration: amortizes loop control and lets the
        // second block's classification overlap the first block's extract.
        while offset + 128 <= data.len() {
            // SAFETY: offset + 128 <= data.len(), so both blocks are readable.
            let m0 = unsafe { step(data.as_ptr().add(offset), &mut carries) }.0;
            push_indexes(m0, offset as u32, out);
            let m1 = unsafe { step(data.as_ptr().add(offset + 64), &mut carries) }.0;
            push_indexes(m1, (offset + 64) as u32, out);
            offset += 128;
        }
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let mask = unsafe { step(data.as_ptr().add(offset), &mut carries) }.0;
            push_indexes(mask, offset as u32, out);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let mask = unsafe { step(block.as_ptr(), &mut carries) }.0 & ((1u64 << rem) - 1);
            push_indexes(mask, offset as u32, out);
        }
    }


    /// Record-aware indexing; structural and terminator masks encode the tape.
    #[target_feature(enable = "neon", enable = "aes")]
    pub fn index_tape(data: &[u8], seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let mut carries = super::CARRY_INIT;
        let mut offset = 0usize;
        // Two blocks per iteration (see index_structurals).
        while offset + 128 <= data.len() {
            // SAFETY: offset + 128 <= data.len(), so both blocks are readable.
            let (m0, t0) = unsafe { step(data.as_ptr().add(offset), &mut carries) };
            push_tape(m0, t0, offset as u32, seps, ends);
            let (m1, t1) = unsafe { step(data.as_ptr().add(offset + 64), &mut carries) };
            push_tape(m1, t1, (offset + 64) as u32, seps, ends);
            offset += 128;
        }
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let (mask, term) = unsafe { step(data.as_ptr().add(offset), &mut carries) };
            push_tape(mask, term, offset as u32, seps, ends);
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            let live = (1u64 << rem) - 1;
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let (mask, term) = unsafe { step(block.as_ptr(), &mut carries) };
            push_tape(mask & live, term & live, offset as u32, seps, ends);
        }
    }

    fn push_tape(structural: u64, term: u64, base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let sep_mask = structural & !term;
        let base_count = seps.len() as u64;
        push_indexes(sep_mask, base, seps);
        let mut t = term;
        while t != 0 {
            let idx = t.trailing_zeros();
            let below = (sep_mask & ((1u64 << idx) - 1)).count_ones() as u64;
            ends.push(((base_count + below) << 32) | (base + idx) as u64);
            t &= t - 1;
        }
    }

    /// Index the full 64-byte blocks of `data` (carries persist across
    /// calls); returns the number of bytes consumed. Streaming primitive.
    #[target_feature(enable = "neon", enable = "aes")]
    pub fn index_tape_partial(data: &[u8], carries: &mut [u64; 2], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let _ = &carries;
        let mut offset = 0usize;
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len().
            let (mask, term) = unsafe { step(data.as_ptr().add(offset), carries) };
            push_tape(mask, term, base + offset as u32, seps, ends);
            offset += 64;
        }
    }

    /// Index one final zero-padded block (end-of-stream only); `live`
    /// masks off the padding bits.
    #[target_feature(enable = "neon", enable = "aes")]
    pub fn index_tape_block(block: &[u8; 64], live: u64, carries: &mut [u64; 2], base: u32, seps: &mut Vec<u32>, ends: &mut Vec<u64>) {
        let _ = &carries;
        // SAFETY: block is a readable 64-byte buffer.
        let (mask, term) = unsafe { step(block.as_ptr(), carries) };
        push_tape(mask & live, term & live, base, seps, ends);
    }

    /// Count NDJSON line terminators with the generated quote/escape-aware
    /// newline step.
    #[target_feature(enable = "neon", enable = "aes")]
    pub fn index_ndjson_lines(data: &[u8]) -> u64 {
        let mut carries = super::CARRY_INIT;
        let mut offset = 0usize;
        let mut count = 0u64;
        while offset + 128 <= data.len() {
            // SAFETY: offset + 128 <= data.len(), so both blocks are readable.
            let (_, t0) = unsafe { step(data.as_ptr().add(offset), &mut carries) };
            let (_, t1) = unsafe { step(data.as_ptr().add(offset + 64), &mut carries) };
            count += t0.count_ones() as u64 + t1.count_ones() as u64;
            offset += 128;
        }
        while offset + 64 <= data.len() {
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let (_, term) = unsafe { step(data.as_ptr().add(offset), &mut carries) };
            count += term.count_ones() as u64;
            offset += 64;
        }
        let rem = data.len() - offset;
        if rem > 0 {
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            let live = (1u64 << rem) - 1;
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let (_, term) = unsafe { step(block.as_ptr(), &mut carries) };
            count += (term & live).count_ones() as u64;
        }
        count
    }

    #[target_feature(enable = "neon", enable = "aes")]
    unsafe fn step(ptr: *const u8, carries: &mut [u64; 2]) -> (u64, u64) {
        // SAFETY: caller guarantees 64 readable bytes at `ptr`.
        let (b0, b1, b2, b3) = unsafe {
            (
                vld1q_u8(ptr),
                vld1q_u8(ptr.add(16)),
                vld1q_u8(ptr.add(32)),
                vld1q_u8(ptr.add(48)),
            )
        };
        let v0 = 0x5555555555555555u64;
        let v1 = eq_mask(b0, b1, b2, b3, 92u8); // class "\\"
        let v2 = v0 ^ v1;
        let v3 = { let (partial, c1) = v0.overflowing_add(v2); let (sum, c2) = partial.overflowing_add(carries[0]); carries[0] = (c1 | c2) as u64; sum };
        let v4 = v0 ^ v3;
        let v5 = eq_mask(b0, b1, b2, b3, 34u8); // class "\""
        let v6 = v5 & v4;
        let v7 = { let parity = prefix_xor(v6) ^ carries[1]; carries[1] = ((parity as i64) >> 63) as u64; parity };
        let v8 = !v7;
        let v9 = eq_mask(b0, b1, b2, b3, 10u8); // class "\n"
        let v10 = v9 & v8;
        (v10, v10 & v9)
    }

    /// NEON has no movemask: AND each lane with its bit value, then fold the
    /// four 16-byte compare results to one dense `u64` (bit j ⇔ byte j) with
    /// three pairwise adds — bit-identical to x86 `movemask`/`cmpeq_epi8_mask`.
    #[target_feature(enable = "neon")]
    fn movemask(c0: uint8x16_t, c1: uint8x16_t, c2: uint8x16_t, c3: uint8x16_t) -> u64 {
        let bits = vreinterpretq_u8_u64(vdupq_n_u64(0x8040_2010_0804_0201));
        let s0 = vpaddq_u8(vandq_u8(c0, bits), vandq_u8(c1, bits));
        let s1 = vpaddq_u8(vandq_u8(c2, bits), vandq_u8(c3, bits));
        let s2 = vpaddq_u8(s0, s1);
        let s3 = vpaddq_u8(s2, s2);
        vgetq_lane_u64::<0>(vreinterpretq_u64_u8(s3))
    }

    #[target_feature(enable = "neon")]
    fn eq_mask(b0: uint8x16_t, b1: uint8x16_t, b2: uint8x16_t, b3: uint8x16_t, byte: u8) -> u64 {
        let needle = vdupq_n_u8(byte);
        movemask(vceqq_u8(b0, needle), vceqq_u8(b1, needle), vceqq_u8(b2, needle), vceqq_u8(b3, needle))
    }

    /// Carryless multiply by all-ones = inclusive prefix XOR. PMULL
    /// (`vmull_p64`) stands in for x86 PCLMULQDQ; the low 64 bits are the
    /// result.
    #[target_feature(enable = "neon", enable = "aes")]
    fn prefix_xor(mask: u64) -> u64 {
        vmull_p64(mask, !0u64) as u64
    }

    /// Branchless bit decoding (simdjson flatten_bits): write indexes in
    /// unconditional chunks of 8, then expose only the popcount-many real
    /// entries.
    #[inline]
    fn push_indexes(mut mask: u64, base: u32, out: &mut Vec<u32>) {
        let count = mask.count_ones() as usize;
        if count == 0 {
            return;
        }
        let len = out.len();
        out.reserve(count + 8);
        // SAFETY: capacity covers len + count + 8; chunked writes overshoot
        // by at most 7 entries and set_len exposes only the real ones.
        unsafe {
            let mut ptr = out.as_mut_ptr().add(len);
            let mut remaining = count as isize;
            while remaining > 0 {
                let mut j = 0;
                while j < 8 {
                    *ptr.add(j) = base + mask.trailing_zeros();
                    mask &= mask.wrapping_sub(1);
                    j += 1;
                }
                ptr = ptr.add(8);
                remaining -= 8;
            }
            out.set_len(len + count);
        }
    }
}

}

pub use self::generated::*;
