//! IR-to-Rust code generation.
//!
//! [`emit`] turns a bitstream [`Graph`] into a self-contained Rust source
//! file with no dependency on this crate: a public `index_structurals`
//! entry point that runtime-dispatches between an AVX2+PCLMULQDQ kernel and
//! a portable scalar fallback. Both kernels run the same blockwise node
//! schedule the interpreter does, so the three implementations are
//! differential-testable against each other.
//!
//! Emission is a single pass over the graph: nodes are already in
//! topological order, every node becomes one `let` binding, and stateful
//! nodes (`ShiftLeft1`, `PrefixXor`, `Add`) get a slot in a carry array that
//! lives across blocks. The two kernels share these per-node lines verbatim
//! except for `Class` nodes, where the byte-comparison primitive differs.

use crate::ir::{Graph, Op};
use std::fmt::Write;

/// Codegen rejected the graph (currently only: a character class too large
/// for compare-based classification).
#[derive(Debug)]
pub struct CodegenError(pub String);

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl std::error::Error for CodegenError {}

/// Largest class emitted as an OR of byte compares; bigger classes need the
/// (future) shuffle-based classifier.
const MAX_CLASS_BYTES: usize = 8;

/// Which kernel a step body is being emitted for.
#[derive(Clone, Copy, PartialEq)]
enum Flavor {
    Avx2,
    Fallback,
}

/// Emit a complete generated source file for `graph`.
pub fn emit(graph: &Graph, format_name: &str) -> Result<String, CodegenError> {
    let output = graph.output();

    // Assign carry slots to stateful nodes.
    let mut carry_slot = vec![usize::MAX; graph.nodes().len()];
    let mut carry_count = 0usize;
    for (i, op) in graph.nodes().iter().enumerate() {
        if matches!(op, Op::ShiftLeft1(_) | Op::PrefixXor(_) | Op::Add(_, _)) {
            carry_slot[i] = carry_count;
            carry_count += 1;
        }
    }

    let uses_class = graph.nodes().iter().any(|op| matches!(op, Op::Class(_)));
    let uses_prefix_xor = graph
        .nodes()
        .iter()
        .any(|op| matches!(op, Op::PrefixXor(_)));

    for op in graph.nodes() {
        if let Op::Class(class) = op {
            let n = class.members().count();
            if n > MAX_CLASS_BYTES {
                return Err(CodegenError(format!(
                    "character class with {n} bytes exceeds the compare-based \
                     limit of {MAX_CLASS_BYTES}"
                )));
            }
        }
    }

    // Pieces that differ depending on whether the graph carries state.
    let carry_decl = if carry_count > 0 {
        format!("        let mut carries = [0u64; {carry_count}];\n")
    } else {
        String::new()
    };
    let carry_param = if carry_count > 0 {
        format!(", carries: &mut [u64; {carry_count}]")
    } else {
        String::new()
    };
    let carry_arg = if carry_count > 0 { ", &mut carries" } else { "" };

    let mut code = String::new();

    let _ = write!(
        code,
        r#"// Generated by vexel from format `{format_name}`. Do not edit by hand;
// regenerate with `cargo run --example generate` (in-tree) or the vexel CLI.
//
// Structural indexer: appends to `out` the byte offset of every set bit in
// the format's output bitstream (its structural positions). Self-contained:
// depends only on std.

/// Index the structural positions of `data` into `out`.
pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {{
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2")
        && std::arch::is_x86_feature_detected!("pclmulqdq")
    {{
        // SAFETY: the required target features were just detected.
        unsafe {{ avx2::index_structurals(data, out) }};
        return;
    }}
    fallback::index_structurals(data, out);
}}

/// Portable kernel, public so the dispatch-bypassed path stays testable.
pub mod fallback {{
    pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {{
{carry_decl}        let mut offset = 0usize;
        while offset + 64 <= data.len() {{
            let block: &[u8; 64] = data[offset..offset + 64].try_into().unwrap();
            let mask = step(block{carry_arg});
            push_indexes(mask, offset as u32, out);
            offset += 64;
        }}
        let rem = data.len() - offset;
        if rem > 0 {{
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            // Mask off bits that fall in the zero padding.
            let mask = step(&block{carry_arg}) & ((1u64 << rem) - 1);
            push_indexes(mask, offset as u32, out);
        }}
    }}

    #[inline]
    fn step(block: &[u8; 64]{carry_param}) -> u64 {{
"#
    );
    emit_step_body(&mut code, graph, &carry_slot, Flavor::Fallback);
    let _ = write!(code, "        v{}\n    }}\n", output.0);

    if uses_class {
        code.push_str(
            r#"
    #[inline]
    fn eq_mask(block: &[u8; 64], byte: u8) -> u64 {
        let mut mask = 0u64;
        let mut i = 0;
        while i < 64 {
            mask |= ((block[i] == byte) as u64) << i;
            i += 1;
        }
        mask
    }
"#,
        );
    }
    if uses_prefix_xor {
        code.push_str(
            r#"
    #[inline]
    fn prefix_xor(mut x: u64) -> u64 {
        x ^= x << 1;
        x ^= x << 2;
        x ^= x << 4;
        x ^= x << 8;
        x ^= x << 16;
        x ^= x << 32;
        x
    }
"#,
        );
    }
    code.push_str(
        r#"
    #[inline]
    fn push_indexes(mut mask: u64, base: u32, out: &mut Vec<u32>) {
        while mask != 0 {
            out.push(base + mask.trailing_zeros());
            mask &= mask - 1;
        }
    }
}

"#,
    );

    let _ = write!(
        code,
        r#"#[cfg(target_arch = "x86_64")]
mod avx2 {{
    use std::arch::x86_64::*;

    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    pub fn index_structurals(data: &[u8], out: &mut Vec<u32>) {{
{carry_decl}        let mut offset = 0usize;
        while offset + 64 <= data.len() {{
            // SAFETY: offset + 64 <= data.len(), so 64 bytes are readable.
            let mask = unsafe {{ step(data.as_ptr().add(offset){carry_arg}) }};
            push_indexes(mask, offset as u32, out);
            offset += 64;
        }}
        let rem = data.len() - offset;
        if rem > 0 {{
            let mut block = [0u8; 64];
            block[..rem].copy_from_slice(&data[offset..]);
            // SAFETY: block is a readable 64-byte buffer. Pad bits masked.
            let mask = unsafe {{ step(block.as_ptr(){carry_arg}) }} & ((1u64 << rem) - 1);
            push_indexes(mask, offset as u32, out);
        }}
    }}

    #[target_feature(enable = "avx2", enable = "pclmulqdq")]
    unsafe fn step(ptr: *const u8{carry_param}) -> u64 {{
        // SAFETY: caller guarantees 64 readable bytes at `ptr`.
        let (lo, hi) = unsafe {{
            (
                _mm256_loadu_si256(ptr as *const __m256i),
                _mm256_loadu_si256(ptr.add(32) as *const __m256i),
            )
        }};
"#
    );
    emit_step_body(&mut code, graph, &carry_slot, Flavor::Avx2);
    let _ = write!(code, "        v{}\n    }}\n", output.0);

    if uses_class {
        code.push_str(
            r#"
    #[target_feature(enable = "avx2")]
    fn eq_mask(lo: __m256i, hi: __m256i, byte: u8) -> u64 {
        let needle = _mm256_set1_epi8(byte as i8);
        let lo_bits = _mm256_movemask_epi8(_mm256_cmpeq_epi8(lo, needle)) as u32 as u64;
        let hi_bits = _mm256_movemask_epi8(_mm256_cmpeq_epi8(hi, needle)) as u32 as u64;
        lo_bits | (hi_bits << 32)
    }
"#,
        );
    }
    if uses_prefix_xor {
        code.push_str(
            r#"
    #[target_feature(enable = "pclmulqdq")]
    fn prefix_xor(mask: u64) -> u64 {
        let ones = _mm_set1_epi8(-1);
        let value = _mm_set_epi64x(0, mask as i64);
        let product = _mm_clmulepi64_si128::<0>(value, ones);
        _mm_cvtsi128_si64(product) as u64
    }
"#,
        );
    }
    code.push_str(
        r#"
    /// Branchless bit decoding (simdjson flatten_bits): write indexes in
    /// unconditional chunks of 8, then expose only the popcount-many real
    /// entries.
    #[inline]
    fn push_indexes(mut mask: u64, base: u32, out: &mut Vec<u32>) {
        let count = mask.count_ones() as usize;
        if count == 0 {
            return;
        }
        let len = out.len();
        out.reserve(count + 8);
        // SAFETY: capacity covers len + count + 8; chunked writes overshoot
        // by at most 7 entries and set_len exposes only the real ones.
        unsafe {
            let mut ptr = out.as_mut_ptr().add(len);
            let mut remaining = count as isize;
            while remaining > 0 {
                let mut j = 0;
                while j < 8 {
                    *ptr.add(j) = base + mask.trailing_zeros();
                    mask &= mask.wrapping_sub(1);
                    j += 1;
                }
                ptr = ptr.add(8);
                remaining -= 8;
            }
            out.set_len(len + count);
        }
    }
}
"#,
    );

    Ok(code)
}

/// Emit one `let vN = ...;` line per node. Shared between kernels except for
/// the `Class` byte-comparison primitive.
fn emit_step_body(code: &mut String, graph: &Graph, carry_slot: &[usize], flavor: Flavor) {
    let class_args = match flavor {
        Flavor::Avx2 => "lo, hi",
        Flavor::Fallback => "block",
    };
    for (i, op) in graph.nodes().iter().enumerate() {
        let line = match *op {
            Op::Class(class) => {
                let compares: Vec<String> = class
                    .members()
                    .map(|b| format!("eq_mask({class_args}, {b}u8)"))
                    .collect();
                let label: String = class.members().map(|b| b.escape_ascii().to_string()).collect();
                format!("let v{i} = {}; // class \"{label}\"", compares.join(" | "))
            }
            Op::Const(pattern) => format!("let v{i} = {pattern:#018x}u64;"),
            Op::Not(a) => format!("let v{i} = !v{};", a.0),
            Op::And(a, b) => format!("let v{i} = v{} & v{};", a.0, b.0),
            Op::Or(a, b) => format!("let v{i} = v{} | v{};", a.0, b.0),
            Op::Xor(a, b) => format!("let v{i} = v{} ^ v{};", a.0, b.0),
            Op::ShiftLeft1(a) => {
                let k = carry_slot[i];
                format!(
                    "let v{i} = {{ let shifted = (v{a} << 1) | carries[{k}]; \
                     carries[{k}] = v{a} >> 63; shifted }};",
                    a = a.0
                )
            }
            Op::PrefixXor(a) => {
                let k = carry_slot[i];
                format!(
                    "let v{i} = {{ let parity = prefix_xor(v{a}) ^ carries[{k}]; \
                     carries[{k}] = ((parity as i64) >> 63) as u64; parity }};",
                    a = a.0
                )
            }
            Op::Add(a, b) => {
                let k = carry_slot[i];
                format!(
                    "let v{i} = {{ let (partial, c1) = v{a}.overflowing_add(v{b}); \
                     let (sum, c2) = partial.overflowing_add(carries[{k}]); \
                     carries[{k}] = (c1 | c2) as u64; sum }};",
                    a = a.0,
                    b = b.0
                )
            }
        };
        let _ = writeln!(code, "        {line}");
    }
}
