name: ci

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            runtime_tests: true
          - runner: macos-latest
            runtime_tests: true
          - runner: ubuntu-24.04-arm
            runtime_tests: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup default stable
      - run: cargo fmt --check
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test --all-targets --features cli,bgzf
        if: matrix.runtime_tests
      - run: cargo test --lib --features cli,bgzf
        if: ${{ !matrix.runtime_tests }}
      - run: cargo build --release --features cli,bgzf
